### ISSUE TITLE
Docs link on buildbot.net is broken

### ISSUE THREAD

**Issue by larkost** [buildbot/buildbot#7990] opened 2024-09-05 20:40 UTC
Currently the "Get Started" -> "Read the Docs" link on buildbot.net is broken. It leads to a 404 error at:
https://buildbot.net/buildbot/docs/current/index.html

**Comment by pmisik** [comment] 2024-09-09 18:42
Hi,

It looks like your report is duplicate of https://github.com/buildbot/buildbot-website/issues/88
There is already PR to fix it https://github.com/buildbot/buildbot-website/pull/87

So it needs to be reviewed, merged and deployed on buildbot.net.

**Comment by p12tic** [comment] 2024-09-27 12:17
https://github.com/buildbot/buildbot-website/pull/87 has been merged and the website will be redeployed shortly.

**Comment by p12tic** [comment] 2024-09-27 12:17
Thanks for the bug report, it's a pity it took a while for me to notice the open pull requests.

**Closed by p12tic** 2024-09-27 12:17 UTC
Labels: bug
