### ISSUE TITLE
buildbot try --get-builder-names returns nothing

### ISSUE THREAD

**Issue by jmsy00** [buildbot/buildbot#3109] opened 2017-04-11 14:22 UTC
I have a Try_Userpass scheduler setup and I'm able to send diffs and initiate builds correctly, but nothing is returned back to the caller on stdout/stderr.  The docs indicate that if 'waiting' a status message should at least print out every 60 seconds or so, but this is not occuring.

passing the global --verbose option does show some status output and if querying for build names, those also show up.

Did 'buildbot try' ever return build output back to the caller in previous versions?
Regardless, is there a way to get it to return the stderr output of the build?

buildbot 0.9.5
twisted 17.1.0
python 2.7.13

thanks,
James

**Comment by tardyp** [comment] 2017-04-11 16:19
Hi James,
The try functionality is deprecated in favor of the REST api. (probably I need to document that better)
There are probably some of its functionality which depended on the status API which are not working anymore including build status.

I think that @verm did an attempt at implementing a command line tool similar to try with the REST api, not sure if he published the code yet.

**Comment by tardyp** [comment] 2017-04-11 16:32
duplicate of https://github.com/buildbot/buildbot/issues/3110

**Closed by tardyp** 2017-04-11 16:32 UTC
Labels: try_scheduler
