### ISSUE TITLE
Dynamically generate choices by extending ChoiceStringParameter 

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3869] opened 2018-01-04 09:25 UTC
Referencing to http://docs.buildbot.net/current/manual/cfg-schedulers.html#choicestringparameter, 
> Note that for some use cases, the choices need to be generated dynamically. This can be done via subclassing and overriding the ‘getChoices’ member function. An example of this is provided by the source for the InheritBuildParameter class.

My code piece doesn't work:
```python
from buildbot.schedulers.forcesched import ForceScheduler, ChoiceStringParameter

class BranchChoiceStringParameter(ChoiceStringParameter):
    type = ChoiceStringParameter.type
    name = "branch"
    def getChoices(self, master, scheduler, buildername):
        return ['1', '2', '3']

sched = ForceScheduler(...,
    properties=[
        BranchChoiceStringParameter(
                    name="Branch",
                    label=u"branch",
                    default="QSMobile_Depot",
                    size=20),
            ])
```
Buildbot version: 0.9.11

**Comment by tardyp** [comment] 2018-01-04 09:46
duplicate of #2952

**Closed by tardyp** 2018-01-04 09:46 UTC
