### ISSUE TITLE
assertion when triggering sub build from try build

### ISSUE THREAD

**Issue by hurricanechristian** [buildbot/buildbot#4773] opened 2019-05-19 07:25 UTC
Hi,

I've been playing with try builds, and want to get a patch passed down to sub builds the build  jobs have the source layed out in the same way and they can trigger fine if I set `alwaysUseLatest=True,` but I want to pass the patch down. I get the following crash each time I remove that setting.

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/buildbot/process/buildstep.py", line 566, in startStep
    self.results = yield self.run()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/buildbot/process/buildstep.py", line 566, in startStep
    self.results = yield self.run()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 258, in run
    ss_for_trigger = self.prepareSourcestampListForTrigger()
  File "/usr/local/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 167, in prepareSourcestampListForTrigger
    ss_for_trigger[ss.codebase] = ss.asDict()
  File "/usr/local/lib/python3.6/site-packages/buildbot/process/buildrequest.py", line 137, in asDict
    ), result
builtins.AssertionError: {'branch': 'foo', 'revision': None, 'repository': 'code', 'project': '', 'codebase': '', 'patch_level': 0, 'patch_body': b'Index: MyPatch...', 'patch_subdir': '', 'patch_author': 'me', 'patch_comment': '"trigger build (by me)"'}

However if I move the step out of the config and into the try scheduler, it triggers both. But I want to be able to link the two together - is this a bug, or am I doing something wrong? Do I need to define a codebase?

Thanks

**Comment by p12tic** [comment] 2021-03-01 20:32
Closing as duplicate of #5165.

**Closed by p12tic** 2021-03-01 20:32 UTC
Labels: bug

**Comment by aj062** [comment] 2021-03-03 23:26
This should be fixed by https://github.com/buildbot/buildbot/pull/5827
