### ISSUE TITLE
Trigger step hitting assersion due to patch_body being binary

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#5812] opened 2021-02-25 12:11 UTC
I updated a Buildbot instance from 1.8.2 (python 2) to 2.10.1 (python 3). The trigger step is hitting an assertion.

```Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/buildbot/process/buildstep.py", line 628, in startStep
    self.results = yield self.run()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/buildbot/process/buildstep.py", line 628, in startStep
    self.results = yield self.run()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 284, in run
    ss_for_trigger = self.prepareSourcestampListForTrigger()
  File "/usr/local/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 178, in prepareSourcestampListForTrigger
    ss_for_trigger[ss.codebase] = ss.asDict()
  File "/usr/local/lib/python3.6/site-packages/buildbot/process/buildrequest.py", line 137, in asDict
    ), result
builtins.AssertionError: {'branch': None, 'revision': None, 'repository': '', 'project': '', 'codebase': '', 'patch_level': 0, 'patch_body': b"Index: Tools/ChangeLog\n===================================================================\n--- Tools/ChangeLog\t(revision 273411)\n+++ Tools/ChangeLog\t(working copy)\n@@ -1,3 +1,12 @@\n+2021-02-24  AJ\n+\n+        [build.webkit.org] Stop using deprecated buildbot.status.builder\n===================================================================\n--- Tools/CISupport/build-webkit-org/steps.py\t(revision 273411)\n+++ Tools/CISupport/build-webkit-org/steps.py\t(working copy)\n@@ -21,10 +21,9 @@\n # OF THIS SOFTWARE.\n \n from buildbot.process import buildstep, factory, logobserver, properties\n-from buildbot.process.results import Results\n+from buildbot.process.results import Results, SUCCESS, FAILURE, WARNINGS, SKIPPED, EXCEPTION\n from buildbot.steps import master, shell, transfer, trigger\n from buildbot.steps.source.svn import SVN\n-from buildbot.status.builder import SUCCESS, FAILURE, WARNINGS, SKIPPED, EXCEPTION\n \n from twisted.internet import defer\n \n", 'patch_subdir': '', 'patch_author': '', 'patch_comment': ''}
```

It seems to be hitting this assertion: https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/buildrequest.py#L134, which seems to be due to 'patch_body' being binary instead of string.

The patch is being sent to this buildbot instance from another machine using 'buildbot try' command, that machine is also using latest buildbot (v2.10.1). Both machines have Python 3.6.8.

**Comment by aj062** [comment] 2021-02-25 12:12
@p12tic @tardyp

**Comment by p12tic** [comment] 2021-03-01 20:33
Closing as duplicate of #5165.

**Closed by p12tic** 2021-03-01 20:33 UTC

**Comment by aj062** [comment] 2021-03-03 23:27
This should be fixed by https://github.com/buildbot/buildbot/pull/5827

**Comment by aj062** [comment] 2021-03-03 23:33
@p12tic what do you think about changing the source of patch_body, to make the patch_body string instead of bytes. Storing patch as bytes could lead to various other corner cases when that patch is used. 

For e.g.: in one of a build step, I read the patch body and do something like: re.search(pattern, patch_body), which fails with error: ```builtins.TypeError: cannot use a string pattern on a bytes-like object```

**Comment by p12tic** [comment] 2021-03-04 00:09
The problem with converting patch body to a string is that then we need to handle its encoding which may have edge cases. So we treat it as a bag of bytes.

Why not just decode the patch body explicitly when searching?
