### ISSUE TITLE
Builders page doesn't show any builders.

### ISSUE THREAD

**Issue by chrwen-omicron** [buildbot/buildbot#3970] opened 2018-02-27 09:20 UTC
Since I've upgraded from version 0.9.13 to 1.0.0, my Buildbot instance stops showing builders after some time. I can still see them when enabling "Show old builders" or after restarting the Buildbot.

**Comment by aj062** [comment] 2018-02-28 22:18
I am also noticing this issue after upgrading to 1.0.0

Might be related to https://github.com/buildbot/buildbot/issues/3956

**Comment by aj062** [comment] 2018-03-06 23:51
@tardyp any ideas?

**Comment by aj062** [comment] 2018-03-06 23:54
This is happening on http://nine.buildbot.net/#/builders right now.

<img width="984" alt="screen shot 2018-03-06 at 3 52 59 pm" src="https://user-images.githubusercontent.com/3098702/37065665-90763954-2156-11e8-8b00-b9428cf211c9.png">

**Comment by tardyp** [comment] 2018-03-07 08:37
see #3981 for root cause of this issue.

Closing as duplicate.

**Closed by tardyp** 2018-03-07 08:37 UTC
