### ISSUE TITLE
Forced build never completes

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2858] opened 2017-03-09 16:39 UTC
This ticket is a migrated Trac ticket [2813](http://trac.buildbot.net/ticket/2813)

People contributed to the original ticket: `buildbot@...`, @djmitche
Ticket created on: `May 27 2014`
Ticket last modified on: `Jun 18 2014`

---

It appears that a forced build will never complete _if_ a build is forced on a build slave with max_builds=1 and that slave is already running a build.  In the most recent case where I finally realized what might be happening, I was forcing a run of another build that runs on the same slave.

The build master appears to actually trigger the secondary build (which it shouldn't do because max_builds=1) but then ignores all output from that slave.  The slave finishes but the master ignores its results and, eventually, *all* builds will stall once that slave is scheduled for another build.  I can't guarantee that the next scheduled build is what triggers this state but the master will definitely get locked up at some point.

Once the system is in this state, the only way to fix it is to stop and restart the master.

---

_Comment from_: @dustin
_Date_: `May 27 2014`

Can you include some twistd.log output from the master to indicate what you're seeing?  I'm not sure how it could trigger a build and ignore the output..

**Comment by Frodox** [comment] 2017-07-27 14:43
I can't reproduce it with 0.9.9p2. I suppose to close it.

**Closed** 2017-08-04 13:37 UTC
Labels: bug, needs reproducer
