### ISSUE TITLE
github change hook dialect not working with treq

### ISSUE THREAD

**Issue by morrone** [buildbot/buildbot#3732] opened 2017-11-03 01:26 UTC
I am using buildbot 0.9.12., installed using "pip install buildbot[bundle]" in a virtualenv.

I am finding that the 'github' change hook dialect appears not to work when the "treq" package is installed rather than "txrequests".  (By the way, it would be nice if the documentation for "GitHub hook" was updated to state that dependency.  Right now it is only documented in the "buildbot.util.httpclientservice", which most users won't know is implied by the github hook.)

For whatever reason, I tried installing treq first.  It looks like things are hanging in buildbot/www/hooks/github.py:_get_commit_msg() on this line:

```data = yield res.json()```

I manually dumped information about the URL that it was trying to retrieve, and I am able to use the curl command as the same user on the same node to retrieve the URL.  So I'm sure that my github repo doesn't require a token to access that information.

Eventually, I uninstalled "treq" and installed "txrequests" instead, and now the github change hook seems to be working correctly and generates changes as expected.

treq version 17.8.0
python version 3.6
txrequests version 0.9.5

**Comment by brkindar** [comment] 2018-10-10 10:41
This is still there on buildbot 1.4.0.
Message says I should install either treq or txrequests. 

Besides, with treq I get a failure, but with txrequests a crash (on osx).

**Comment by tardyp** [comment] 2018-10-10 11:46
treq and txrequests are optional dependencies. This is why they are only loaded optionaly, with error message on what to install.

if treq or txrequests do not work on osx, please open another bug

**Comment by brkindar** [comment] 2018-10-10 12:15
Hmm, after several strange behavior with txrequests (crashs and hangs) it seems to be working now.
Since I can't reproduce I wont's say much more...

**Comment by tardyp** [comment] 2018-10-10 12:55
I just verified that treq is supporting .json() and it is correctly unit tested. This bug is quite old (0.9.12) so I will close it. Please reopen with detailled failure from treq if it exist

**Closed by tardyp** 2018-10-10 12:55 UTC
Labels: bug, webhook
