### ISSUE TITLE
bitbucketcloud.py

### ISSUE THREAD

**Issue by n3rio** [buildbot/buildbot#4123] opened 2018-05-30 19:55 UTC
bitbucketcloud.py for the category of pullrequest_fulfilled seens to be outdated, it expets certains fileds in the payload, that, after examine the bitbucket event payload site (https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html) won't match, bitbucketcloud.py end up looking for keys inside the payload dict

**Comment by jerrylogansquare** [comment] 2018-10-25 02:01
i'm sending some pullrequest:created hooks from bitbucket, this file is not processing.  Looks like they updated the payload structure in the past year, but I can't find any information about when they changed.

**Comment by tardyp** [comment] 2018-10-27 11:54
duplicate of #4153

**Closed by tardyp** 2018-10-27 11:54 UTC
