### ISSUE TITLE
Buildbot generates incorrect step name

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3551] opened 2017-08-21 22:24 UTC
If two build steps have same name, buildbot tries to make the name unique by appending string like "_1" in the name (https://git.io/v5U0G).

However, when the step names are renderable, the above logic to append to the name doesn't work. This seems to be regression from https://github.com/buildbot/buildbot/commit/9454a5cf6b3242c00696f98f0735d0beabbb0c7c#diff-55eba84ed1643c9e414ccbb8621ca8e6R127

This issue reproduces when there are two build steps which checkout different folders from same svn repository.

This ultimately produces following error:
```
2017-08-19 20:35:32-0700 [-] Got fatal Exception on DB
        Traceback (most recent call last):
        Failure: sqlalchemy.exc.DataError: (psycopg2.DataError) value too long for type character varying(50)
         [SQL: 'INSERT INTO steps (number, name, buildid, started_at, complete_at, state_string, urls_json) VALUES (%(number)s, %(name)s, %(buildid)s, %(started_at)s, %(complete_at)s, %(state_string)s, %(urls_json)s) RETURNING steps.id'] [parameters: {'complete_at': None, 'name': u"Interpolate('%(kw:name)s-%(kw:codebase)s', **{'codebase': 'myproject', 'name': 'svn'})_1", 'buildid': 3807, 'urls_json': '[]', 'number': 7, 'state_string': u'pending', 'started_at': None}]
```
Notice: 'name': u"Interpolate('%(kw:name)s-%(kw:codebase)s', **{'codebase': 'myproject', 'name': 'svn'})_1"

**Comment by tardyp** [comment] 2017-08-28 08:46
I am not sure exactly what can happen here. It looks like self.name is converted to a string somewhere, but I can't see where it could be the case.

Could you have something specific in your config doing that str(self.name)

**Comment by mokibit** [comment] 2023-12-19 12:08
Hello, 
I have tried to reproduce this bug with step names longer than 50 characters. In all cases,  the step name is not being changed into similar string of the original problem ('u"Interpolate('%(kw:name)s-%(kw:code<....>'), therefore, I will close this bug for now. 
If simiar problem exists in recent version of Buildbot, please open a new issue.

**Closed by mokibit** 2023-12-19 12:08 UTC
