### ISSUE TITLE
Waterfall displays wrong builder names

### ISSUE THREAD

**Issue by tichy3000** [buildbot/buildbot#3942] opened 2018-02-08 15:46 UTC
The builder names in our Waterfall view don't correspond to the underlying links.
We have builder names starting with upper case letters and we have builder names starting with lower case letters.
The displayed names are in alphabetical order without case sensitivity.
The linked builders seem to be ordered by their names WITH case sensitivity, starting with the upper case builder names.

**Comment by tardyp** [comment] 2018-08-22 08:37
duplicate of #3819

**Closed by tardyp** 2018-08-22 08:37 UTC
