### ISSUE TITLE
FailingBuildsetCanceller issues when calling

### ISSUE THREAD

**Issue by toygg96** [buildbot/buildbot#6781] opened 2023-01-27 01:58 UTC
I tried to call FailingBuildsetCanceller according to the api documentation here but it does not work and it does not output anything. 
Docs link: https://docs.buildbot.net/latest/manual/configuration/services/failing_buildset_canceller.html

Tried to test it by cancelling a buildrequest in test_builder while it is running but it does not stop the buildrequest in test_builder2/3 which is part of the same buildset. Any help is appreciated!

**master.cfg** snippet

testBuilders = []
testBuilders.append("test_builder")
testBuilders.append("test_builder2")
testBuilders.append("test_builder3")

failing_bs_canceller_tupples_filter = []
failing_bs_canceller_tupples_filter.append(testBuilders, None, util.SourceStampFilter(project_eq="main_test", "codebase_eq="main_test", repository_eq="main_test", branch_eq="master"))

c["services"].append(
    util.FailingBuildsetCanceller(
        "buildset_canceller",
        failing_bs_canceller_tuppples_filter
    )
)

**Comment by mokibit** [comment] 2023-06-27 11:58
Hi, @toygg96,
I tried to reproduce this bug, but without success. It works for me in all cases which I tested:
1) Scheduler starts running builders sequence each time the branch changes
2) When one builder fails, following builders are not run: they are cancelled, as expected according to documentation

Could it be, that the SourceStampFilter uses incorrect arguments? For example, in default configuration `codebase` and `project` source stamp properties are empty. You could check the values in the `Debug` tab of the build.

**Comment by p12tic** [comment] 2023-08-01 16:08
I will close this issue for now, please reopen once you have more information.

**Closed by p12tic** 2023-08-01 16:08 UTC
