### ISSUE TITLE
Change page is very slow when lots of change

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2988] opened 2017-03-09 16:54 UTC
This ticket is a migrated Trac ticket [3480](http://trac.buildbot.net/ticket/3480)

People contributed to the original ticket: @djmitche, @tardyp
Ticket created on: `Mar 08 2016`
Ticket last modified on: `Mar 15 2016`

---

takes 1.48 second on http://nine.buildbot.net/#/changes
takes 22 seconds on my instance

I believe this is because the ordering and limit is not implemented in db layer, but in data layer, and change table can grow quite large, so this is worth to implement in db layer.

---

**Comment by seankelly** [comment] 2018-08-24 20:04
We recently encountered this. I'm still researching the cause but I believe it's because accessing /changes calls `buildbot.db.changes.getChanges`. This loads every single change into a `Change`.

If this is the case, then I think we should eliminate any way for the UI to call `getChanges` and instead point it at either `getRecentChanges` or a new method that allows fetching a window of changes so an infinite scroll can load the next small N of changes.

**Comment by seankelly** [comment] 2018-09-05 14:01
This was fixed in #3263 and is in 0.9.8.

**Closed by seankelly** 2018-09-05 14:01 UTC
Labels: database, slow
