### ISSUE TITLE
Windows Worker: When TASKKILL fails on 'TERM', does not retry on 'KILL'

### ISSUE THREAD

**Issue by klhowell** [buildbot/buildbot#5844] opened 2021-03-03 03:40 UTC
On my Windows Server 2016 worker, when trying to cancel a Step (either manually or due to timeout), the initial TASKKILL command (without /F) causes an exception, and the forced TASKKILL (with /F) is never run.

> [Broker,client] Unhandled Error
>         Traceback (most recent call last):
>           File "c:\python38\lib\site-packages\twisted\spread\banana.py", line 173, in gotItem
>             self.callExpressionReceived(item)
>           File "c:\python38\lib\site-packages\twisted\spread\banana.py", line 136, in callExpressionReceived
>             self.expressionReceived(obj)
>           File "c:\python38\lib\site-packages\twisted\spread\pb.py", line 621, in expressionReceived
>             method(*sexp[1:])
>           File "c:\python38\lib\site-packages\twisted\spread\pb.py", line 1025, in proto_message
>             self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
>         --- <exception caught here> ---
>           File "c:\python38\lib\site-packages\twisted\spread\pb.py", line 1054, in _recvMessage
>             netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
>           File "c:\python38\lib\site-packages\twisted\spread\flavors.py", line 125, in remoteMessageReceived
>             state = method(*args, **kw)
>           File "c:\python38\lib\site-packages\buildbot_worker\base.py", line 169, in remote_interruptCommand
>             self.command.doInterrupt()
>           File "c:\python38\lib\site-packages\buildbot_worker\commands\base.py", line 189, in doInterrupt
>             self.interrupt()
>           File "c:\python38\lib\site-packages\buildbot_worker\commands\shell.py", line 58, in interrupt
>             self.command.kill("command interrupted")
>           File "c:\python38\lib\site-packages\buildbot_worker\runprocess.py", line 945, in kill
>             self.sendSig("TERM")
>           File "c:\python38\lib\site-packages\buildbot_worker\runprocess.py", line 900, in sendSig
>             subprocess.check_call(
>           File "c:\python38\lib\subprocess.py", line 364, in check_call
>             raise CalledProcessError(retcode, cmd)
>         subprocess.CalledProcessError: Command 'TASKKILL /PID 2204 /T' returned non-zero exit status 128.

I've manually invoked the failing TASKKILL command, and it does fail with error code 128. However, the failure reason that it reports is that one of the child processes in the tree must be killed with '/F'.

> C:\Users\Administrator>TASKKILL /PID 2204 /T
> ERROR: The process with PID 2488 (child process of PID 2344) could not be terminated.
> Reason: This process can only be terminated forcefully (with /F option).
> ...

Because runprocess.py uses the 'check_call()' method without an exception handler, the error code translates to an unhandled python exception and the code never gets to schedule the 'KILL' version of the command (which successfully terminates the process tree when I run it manually).

It looks to me like there either needs to be an exception handler for the win32 path in sendSig() or the method needs to use 'subprocess.call()' instead of 'subprocess.check_call()'.

**Comment by yinyangsx** [comment] 2021-07-14 09:04
Hello, I am also meeting the similar issue, TASKKILL failed with exit status 128.
`2021-07-14 10:29:25+0300 [-] using TASKKILL PID /F /T to kill pid 213464
2021-07-14 10:29:25+0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\application\app.py", line 399, in startReactor
	    self.config, oldstdout, oldstderr, self.profiler, reactor)
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\application\app.py", line 312, in runReactorWithLogging
	    reactor.run()
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\internet\base.py", line 1272, in run
	    self.mainLoop()
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\internet\base.py", line 1281, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\internet\base.py", line 902, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 822, in doTimeout
	    self.kill(msg)
	  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 946, in kill
	    hit = self.sendSig(self.interruptSignal)
	  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 905, in sendSig
	    "TASKKILL /F /PID {0} /T".format(self.process.pid))
	  File "C:\Program Files\Python37\lib\subprocess.py", line 363, in check_call
	    raise CalledProcessError(retcode, cmd)
	subprocess.CalledProcessError: Command 'TASKKILL /F /PID 213464 /T' returned non-zero exit status 128.`

I've manually invoked the failing TASKKILL command, and it does fail with error code 128. From the output, we can see the failure reason is that there is no running instance of the task when killing some child process.
`ERROR: The process with PID 214484 (child process of PID 213096) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 213976 (child process of PID 212212) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 215376 (child process of PID 215556) could not be terminated.
Reason: There is no running instance of the task.
SUCCESS: The process with PID 215556 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 212212 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 215492 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 213196 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 207940 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 207084 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 214124 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 211980 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 213620 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 215100 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 213096 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 210924 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 213264 (child process of PID 214776) has been terminated.
SUCCESS: The process with PID 214776 (child process of PID 208396) has been terminated.
SUCCESS: The process with PID 208396 (child process of PID 213760) has been terminated.
SUCCESS: The process with PID 213760 (child process of PID 212780) has been terminated.
SUCCESS: The process with PID 212780 (child process of PID 211996) has been terminated.
SUCCESS: The process with PID 215312 (child process of PID 213256) has been terminated.
SUCCESS: The process with PID 211996 (child process of PID 213256) has been terminated.
SUCCESS: The process with PID 213256 (child process of PID 28064) has been terminated.`

**Comment by klhowell** [comment] 2021-07-14 20:42
> 2021-07-14 10:29:25+0300 [-] using TASKKILL PID /F /T to kill pid 213464
@yinyangsx It looks like your issue is a bit different from mine, but leads to the same exception. In my case, the version of TASKKILL with the '/F' was never called due to an earlier exception. In your case, TASKKILL is being called with the '/F', but it is returning failure. Your failure looks to me a bit like a race within TASKKILL itself. After this exception, is the process tree successfully killed?

I'd say the fix for both of our issues is to handle the error results from TASKKILL instead of firing unhandled python exceptions.

**Comment by yinyangsx** [comment] 2021-07-15 01:26
> After this exception, is the process tree successfully killed?
I confirm that the process tree was successfully killed, but the job is not terminated, it is still in yellow. I very agree with you that the exceptions from TASKKILL should be handled.

**Comment by yinyangsx** [comment] 2021-07-16 06:38
I have a new idea, I think Buildbot should add the exit code '128' of TISKKILL as a Successful Return Code because code 128 means that the process you attempted to kill wasn't actually running on the target system.

**Comment by p12tic** [comment] 2022-02-03 20:44
This bug is a duplicate of https://github.com/buildbot/buildbot/issues/6140 which has been fixed in #6321.

**Closed by p12tic** 2022-02-03 20:44 UTC
Labels: bug
