### ISSUE TITLE
Bitbucket push hook is not working: Twisted request.args dictionary is empty

### ISSUE THREAD

**Issue by thiagowfx** [buildbot/buildbot#3134] opened 2017-04-20 20:38 UTC
I have set up a buildbot and a repository on Bitbucket and tried to enable its bitbucket push hook:

1. In the bitbucket repo, I added the correct buildbot URL to send the hook to.
2. In the buildbot master config, I added the correct parameter to c['www'] to activate the hook.

However, it is not working. After some investigation, I see the problem is that the Twisted request.args dictionary (in `buildbot/www/hooks/bitbucket.py`) is empty.

I realized that by adding a `log.msg(request.args)`. On the other hand, `request.requestHeaders` is not empty; it is set-up with the correct headers (I compared the logs with the bitbucket request in bitbucket and they match indeed).

The question is: why would the request arguments be empty? Is it an error from Twisted or from Buildbot? I even tried to send custom requests with simpler POST bodies, but in all cases `request.args` was still empty.

* Python version: 2.7.6
* Buildbot version: 0.9.6
* Twisted version: 17.1.0

**Comment by seankelly** [comment] 2017-04-21 01:36
Is there anything in the logs?

**Comment by thiagowfx** [comment] 2017-04-21 01:46
@seankelly: the logs just showed a KeyError Exception, because of the following line

```
payload = json.loads(request.args['payload'][0])
```

in https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/hooks/bitbucket.py

Since `request.args` is an empty dictionary at that point, it fails there.

**Comment by tardyp** [comment] 2017-04-21 09:40
@thiagowfx buildbot is expecting bitbucket to send a POST with the data in form encoding ( Content-Type= application/x-www-form-urlencoded)

It is unclear in bitbucket documentation if this has changed https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-HTTPheaders
github/gitlab allows to configure whether they send the data form-encoded or json-encoded
You can see how this works for github:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/hooks/github.py#L105

maybe you could try to add some debug infor in bitbucket.py, and see what exactly bitbucket is sending.

**Comment by thiagowfx** [comment] 2017-04-21 16:08
I am pretty sure bitbucket is sending application/json as the content type, because I can see exactly what it is sending through it is Web UI (in its repository settings). 

Can we change buildbot.py to expect an application/json instead? I'm not sure whether we can change bitbucket to send an application/x-www-form-urlencoded.

- Thiago

**Comment by thiagowfx** [comment] 2017-04-21 16:11
Take a look at one of the requests:

![image](https://cloud.githubusercontent.com/assets/2840106/25286409/025696ae-2694-11e7-9105-03e3ea9267b2.png)

**Comment by bdbaddog** [comment] 2017-04-23 22:55
I'm seeing failure on bitbucket as well:
Here's the output in my twistd.log

```
2017-04-21T16:46:12-0700 [_GenericHTTPChannelProtocol,91,127.0.0.1] Attempting to load module buildbot.www.hooks.bitbucket
2017-04-21T16:46:12-0700 [_GenericHTTPChannelProtocol,91,127.0.0.1] processing changes from web hook
        Traceback (most recent call last):
        Failure: exceptions.KeyError: 'payload'
```

I took a quick look at the code and it looks like the contents from bitbucket have also changed (in addition to changing from post to json content type).

**Comment by thiagowfx** [comment] 2017-04-23 22:58
I got the same output in `twistd.log` as @bdbaddog. The explanation of this output makes sense once you read my previous comments.

If I understand it correctly, we have two options:

1) make Twist parse `application/json` instead of `application/x-www-form-urlencoded`
2) make Bitbucket send `application/x-www-form-urlencoded` instead of `application/json`

I am not sure if 2) is possible.

**Comment by bdbaddog** [comment] 2017-04-23 23:00
3. Fix standalone bitbucket parse application/json .. (not really an exact fix to this bug, but certainly it'll need updating as well)

**Comment by bdbaddog** [comment] 2017-04-24 01:09
Here's the URL for bitbucket payload doc.  [Bitbucket Payload doc](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html)

**Comment by kkworden** [comment] 2017-06-06 20:58
Any progress on this? I am also getting the same `KeyError`.

As a quick-fix I'm going to write a small Node.js application to intercept the POST request and force it to conform to a buildbot-digestible format, but it would be nice to see official Bitbucket support.

**Comment by bdbaddog** [comment] 2017-06-07 21:05
I have a partial fix in my repo.
https://github.com/bdbaddog/buildbot/tree/bitbucket_webhook

In theory you should only need to pull this file:
master/buildbot/www/hooks/bitbucket.py

I'm working on a proper pull request, but haven't had much time lately.
I've only tested with a mercurial repo.

**Comment by petri** [comment] 2017-12-05 13:07
Same issue. I took the bitbucket.py from @bdbaddog, moved `getChanges` to the handler class and assigned the handler to a module-global `bitbucket` variable. Now the hooks get through. I just started using buildbot so not everything is working but the hook seems to work more or less ok.

**Comment by petri** [comment] 2017-12-05 13:08
@tardyp there have been more changes than just encoding. See the partial fix by @bdbaddog.

**Comment by tardyp** [comment] 2017-12-05 17:40
There have been some fixes recently upstreamed: https://github.com/buildbot/buildbot/pull/3764

Does it work better for you?

**Comment by bdbaddog** [comment] 2017-12-05 18:08
I think bitbucket.org and bitbucket commercial (and commercial cloud) aren't the same codebase and the webhook payload may be different?

**Comment by petri** [comment] 2017-12-05 19:52
@tardyp as soon as the PR gets merged, yes, thanks looks good

**Comment by nilp0inter** [comment] 2018-06-20 13:22
I am experiencing the same issue with the last version of buildbot. Is there anything I can help you with?

**Comment by devrajatverma** [comment] 2018-07-12 10:33
@nilp0inter : same here, do share the solution if you found one

**Comment by davl1** [comment] 2018-10-19 11:44
Hi, are there any versions of BuildBot that don't have the payload KeyError problem with bitbucket webhooks?  I just installed buildbot using pip with python 2.7, and that seems to still have the problem.

Is there a workaround?

Thanks.

davl1

**Comment by devrajatverma** [comment] 2018-10-19 12:29
look at your twisted log
there should be a key not found error
i don't have remember which key is they removed i guess it's "project", you have to comment out a line in the python file which parses that payload (line 75)
anaconda3/envs/myenv/lib/python3.6/site-packages/buildbot/www/hooks/bitbucketcloud.py

**Comment by tardyp** [comment] 2018-10-19 13:10
Would be cool if any of the bitbucket cloud user could share a patch or a payload so that we can fix that bug as a community.
thanks

**Comment by davl1** [comment] 2018-10-19 13:11
Thank you for the quick response!  

I have been using the "bitbucket" plugin, which fails with a "KeyError" looking for "payload".  

I just tried the bitbucketcloud plugin and the twistd.log file says "The dialect specified, 'bitbucket', wasn't whitelisted in change_hook".  If I'm reading the code correctly, the dialect is determined from the request uri.

Frankly, I'm not clear on the difference between bitbucketcloud and bitbucket.  It seems adding "bitbucket" to the change_hook dialect list at least gets me into the plugin, but I'm completely new to this (started yesterday) so I could be doing something fundamentally wrong.

Right now I'm spending time trying to intercept the bitbucket webhook, modify it so that it has what the bitbucket plugin is expecting, and forward it to the bitbucket plugin, but that seems like a less than ideal solution.

Can you tell me where I can find the difference between bitbucketcloud and bitbucket plugins?  

Thanks again!

**Comment by devrajatverma** [comment] 2018-10-19 13:18
do share the code where you configuring the change hook

**Comment by devrajatverma** [comment] 2018-10-19 13:29
Got it,
sorry i didn't tried the plugin way

**Comment by davl1** [comment] 2018-10-19 14:47
@devrajatverma 

I'm not all the way there yet, but thanks to you pointing out that I should be using bitbucketcloud, I am a lot closer.  I added the missing key (all hardcoded for now) to the event payload and got a response of:  "1 change found" instead of the "500" that I had been  getting.

Thanks!

**Comment by cdenney1234** [comment] 2018-10-19 16:34
+2pin

**Comment by tardyp** [comment] 2018-10-22 07:08
ah. So this is just the wrong plugin being used? Closing then..

**Closed by tardyp** 2018-10-22 07:08 UTC
Labels: bug, webhook

**Comment by davl1** [comment] 2018-10-22 14:10
@tardyp , there were two problems.  

1.  I was using the wrong plugin (bitbucket vs bitbucketcloud).  
2.  bitbucketcloud is expecting a "project" element within the "repository" node, and a "name" value for the "project" element.  Those values are not in the bitbucket webhook payload.

I'm using a Python script to intercept the bitbucket webhook, modify the payload (and change the Content-Length header to reflect the size of the modified payload), and forward it to the Buildbot change_hook.

**Comment by kravietz** [comment] 2018-12-06 16:00
@davl1 I have just experienced the same problem and I'm not sure what is the root cause - is it caused by either `bitbucket` or `bitbucketcloud` out-of-date plugin definitions in Buildbot or something else?

**Comment by davl1** [comment] 2018-12-06 20:20
Pawel,

I am using a Python script to deal with the incompatibility..  The data 
in the bitbucket webhook post is json that has a "repository" node, 
which contains a "project" node.  The Python script adds a "name" value 
to the project node, and forwards the webhook http call to the 
bitbucketcloud change hook.

The script basically does this:

1.  Listen (port 443 for https or 80 for http) for the bitbucket webhook 
POST.
2.  Read the json payload.
1.  Convert the json data to a dict using json.loads.
2.  Add the "name" element with something like:  json_dict 
["repository"] ["project"] = {"name":project_name}
3.  Convert the dict back to json with json.dumps
4.  Forward the call to the buildbot bitbucketcloud (http://<buildbot 
server:port>/change_hook/bitbucketcloud

That has been working for a few months now.  It's not heavily used, but 
it seems to do everything needed.

Thanks.

bitbucket webhook adds a "name" element to the

**Comment by kravietz** [comment] 2018-12-06 20:43
@davl1 I was wondering if the issue is caused by Buildbot webhook driver in `buildbot/www/hooks/bitbucketcloud.py` being out of date or something else? I mean why exactly Builbot expects that `project` field that Bitbucket doesn't send? Because if the driver is out of date then I can just write a patch and submit a pull request so that it's fixed for good.

**Comment by davl1** [comment] 2018-12-06 21:08
@Pawel,

I think I read that there are two different versions of bitbucket (maybe 
commercial and free?) and Buildbot is configured for one but not the 
other.  I think Tardyp would have more information.  I was never able to 
get it to work without making that change.

Thanks.
