### ISSUE TITLE
UnauthorizedLogin should be handled gracefully

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4164] opened 2018-06-22 00:14 UTC
In case an unauthorized worker tries to connect to master, there is an exception in master twistd.log. This should be handled gracefully. When there are multiple such workers, these exceptions fills up all the logs. https://github.com/buildbot/buildbot/issues/4163 makes the logs worse.

Logs:
```
2018-06-21 17:11:46-0700 [Broker,131,127.0.0.1] Unhandled Error 
        Traceback (most recent call last):
          File "/Library/Python/2.7/site-packages/twisted/spread/pb.py", line 1631, in remote_respond
            d = self.portal.login(self, mind, IPerspective)
          File "/Library/Python/2.7/site-packages/twisted/cred/portal.py", line 119, in login 
            return maybeDeferred(self.checkers[i].requestAvatarId, credentials
          File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw) 
          File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/Library/Python/2.7/site-packages/buildbot/pbmanager.py", line 212, in requestAvatarId
            raise error.UnauthorizedLogin()
        twisted.cred.error.UnauthorizedLogin: 
```

**Comment by seankelly** [comment] 2018-06-22 02:40
Duplicate of #4047.

**Closed by seankelly** 2018-06-22 02:40 UTC
