### ISSUE TITLE
no 'fromRef' key in pull request create json from bitbucket cloud

### ISSUE THREAD

**Issue by jerrylogansquare** [buildbot/buildbot#4374] opened 2018-10-25 01:35 UTC
https://github.com/buildbot/buildbot/blob/505902bdf1bd0849e9671321a6f540ae9f085229/master/buildbot/www/hooks/bitbucketcloud.py#L145

I get this error when sending pullrequest:created:
`
File "/usr/local/lib/python2.7/dist-packages/buildbot/www/hooks/bitbucketcloud.py", line 145, in handle_pullrequest
	    'revision': payload['pullrequest']['fromRef']['commit']['hash'],
	exceptions.KeyError: 'fromRef'
`
This is the json content

`
{
  "pullrequest": {
    "rendered": {
      "description": {
        "raw": "* change 1\r\n* another change\r\n* another change\r\n* another change\r\n* just another test",
        "markup": "markdown",
        "html": "<ul>\n<li>change 1</li>\n<li>another change</li>\n<li>another change</li>\n<li>another change</li>\n<li>just another test</li>\n</ul>",
        "type": "rendered"
      },
      "title": {
        "raw": "NGCPC-6171 do not merge",
        "markup": "markdown",
        "html": "<p>NGCPC-6171 do not merge</p>",
        "type": "rendered"
      }
    },
    "merge_commit": null,
    "description": "* change 1\r\n* another change\r\n* another change\r\n* another change\r\n* just another test",
    "links": {
      "decline": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/pullrequests/80/decline"
      },
      "commits": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/pullrequests/80/commits"
      },
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/pullrequests/80"
      },
      "comments": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/pullrequests/80/comments"
      },
      "merge": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/pullrequests/80/merge"
      },
      "html": {
        "href": "https://bitbucket.org/sandcsw/neo_modules_common/pull-requests/80"
      },
      "activity": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/pullrequests/80/activity"
      },
      "diff": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/pullrequests/80/diff"
      },
      "approve": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/pullrequests/80/approve"
      },
      "statuses": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/pullrequests/80/statuses"
      }
    },
    "title": "NGCPC-6171 do not merge",
    "close_source_branch": false,
    "reviewers": [],
    "destination": {
      "commit": {
        "type": "commit",
        "hash": "7d5216f375cf",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/commit/7d5216f375cf"
          },
          "html": {
            "href": "https://bitbucket.org/sandcsw/neo_modules_common/commits/7d5216f375cf"
          }
        }
      },
      "branch": {
        "name": "master"
      },
      "repository": {
        "full_name": "sandcsw/neo_modules_common",
        "type": "repository",
        "name": "neo_modules_common",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common"
          },
          "html": {
            "href": "https://bitbucket.org/sandcsw/neo_modules_common"
          },
          "avatar": {
            "href": "https://bytebucket.org/ravatar/%7Ba0c87d29-9970-421c-9bb3-b65530918de7%7D?ts=1312880"
          }
        },
        "uuid": "{a0c87d29-9970-421c-9bb3-b65530918de7}"
      }
    },
    "comment_count": 0,
    "closed_by": null,
    "summary": {
      "raw": "* change 1\r\n* another change\r\n* another change\r\n* another change\r\n* just another test",
      "markup": "markdown",
      "html": "<ul>\n<li>change 1</li>\n<li>another change</li>\n<li>another change</li>\n<li>another change</li>\n<li>just another test</li>\n</ul>",
      "type": "rendered"
    },
    "source": {
      "commit": {
        "type": "commit",
        "hash": "aa4327ff3f54",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common/commit/aa4327ff3f54"
          },
          "html": {
            "href": "https://bitbucket.org/sandcsw/neo_modules_common/commits/aa4327ff3f54"
          }
        }
      },
      "branch": {
        "name": "NGCPC-6171_do_not_merge"
      },
      "repository": {
        "full_name": "sandcsw/neo_modules_common",
        "type": "repository",
        "name": "neo_modules_common",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common"
          },
          "html": {
            "href": "https://bitbucket.org/sandcsw/neo_modules_common"
          },
          "avatar": {
            "href": "https://bytebucket.org/ravatar/%7Ba0c87d29-9970-421c-9bb3-b65530918de7%7D?ts=1312880"
          }
        },
        "uuid": "{a0c87d29-9970-421c-9bb3-b65530918de7}"
      }
    },
    "created_on": "2018-10-25T01:19:41.973478+00:00",
    "state": "OPEN",
    "task_count": 0,
    "participants": [],
    "reason": "",
    "updated_on": "2018-10-25T01:19:42.003401+00:00",
    "author": {
      "username": "jerry_morrow_sandc",
      "display_name": "Jerry Morrow",
      "account_id": "557058:c354565e-2288-404e-bf68-86d85649a033",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/jerry_morrow_sandc"
        },
        "html": {
          "href": "https://bitbucket.org/jerry_morrow_sandc/"
        },
        "avatar": {
          "href": "https://bitbucket.org/account/jerry_morrow_sandc/avatar/"
        }
      },
      "type": "user",
      "nickname": "jerry_morrow_sandc",
      "uuid": "{67ca568a-532e-4df9-804a-58be0bdf774e}"
    },
    "type": "pullrequest",
    "id": 80
  },
  "actor": {
    "username": "jerry_morrow_sandc",
    "display_name": "Jerry Morrow",
    "account_id": "557058:c354565e-2288-404e-bf68-86d85649a033",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/users/jerry_morrow_sandc"
      },
      "html": {
        "href": "https://bitbucket.org/jerry_morrow_sandc/"
      },
      "avatar": {
        "href": "https://bitbucket.org/account/jerry_morrow_sandc/avatar/"
      }
    },
    "type": "user",
    "nickname": "jerry_morrow_sandc",
    "uuid": "{67ca568a-532e-4df9-804a-58be0bdf774e}"
  },
  "repository": {
    "scm": "git",
    "website": "",
    "name": "neo_modules_common",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/sandcsw/neo_modules_common"
      },
      "html": {
        "href": "https://bitbucket.org/sandcsw/neo_modules_common"
      },
      "avatar": {
        "href": "https://bytebucket.org/ravatar/%7Ba0c87d29-9970-421c-9bb3-b65530918de7%7D?ts=1312880"
      }
    },
    "project": {
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/teams/sandcsw/projects/NEO"
        },
        "html": {
          "href": "https://bitbucket.org/account/user/sandcsw/projects/NEO"
        },
        "avatar": {
          "href": "https://bitbucket.org/account/user/sandcsw/projects/NEO/avatar/32"
        }
      },
      "type": "project",
      "uuid": "{858631e8-3e3f-41fe-9f37-f49688e4d7f3}",
      "key": "NEO",
      "name": "NEO"
    },
    "full_name": "sandcsw/neo_modules_common",
    "owner": {
      "username": "sandcsw",
      "type": "team",
      "display_name": "sandcsw",
      "uuid": "{bfc3989d-a9af-4b0f-a2c6-a0e0fee57816}",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/teams/sandcsw"
        },
        "html": {
          "href": "https://bitbucket.org/sandcsw/"
        },
        "avatar": {
          "href": "https://bitbucket.org/account/sandcsw/avatar/"
        }
      }
    },
    "type": "repository",
    "is_private": true,
    "uuid": "{a0c87d29-9970-421c-9bb3-b65530918de7}"
  }
}
`

**Comment by jerrylogansquare** [comment] 2018-10-26 21:18
do you (the maintainers) want me to work on this?

**Comment by tardyp** [comment] 2018-10-27 11:55
hi @jerrylogansquare 
yes please, we would apreciate that the bitbucket community can update the hook to be compatible.
this is a dupe of #4153 where someone propose a working fix. 
Remaining work is to update the unit tests for it

**Closed by tardyp** 2018-10-27 11:55 UTC
