### ISSUE TITLE
Worker stuck in building state after worker disconnection

### ISSUE THREAD

**Issue by jpflori** [buildbot/buildbot#5745] opened 2021-01-08 10:11 UTC
The connection got lost but the build went on, or rather kept waiting for worker feedback.
I tried to stop the build by clicking the stop button but it does not work and stays in yellow/building.
It only adds new lines with:
`no reason`
or
`[Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion. ]`

I'm working on giving a fuller log and precise repro instructions.

**Comment by jpflori** [comment] 2021-01-08 13:52
I tried the following which did not reproduce the error:
* start a build honored by a libvirt worker,
* virsh destroy worker
* the build was correctly cancelled

**Comment by jpflori** [comment] 2021-01-08 14:00
When I stopped the master, I got the following logs:
2021-01-08 12:38:08+0100 [-] Initiating clean shutdown
2021-01-08 12:38:08+0100 [-]  <Build my_build number:666 results:cancelled>: stopping build: Master Shutdown 5
2021-01-08 12:38:08+0100 [-] RemoteCommand.interrupt <RemoteShellCommand '[......]'> Master Shutdown
2021-01-08 12:38:08+0100 [-]  but this RemoteCommand is already inactive

**Comment by jpflori** [comment] 2021-01-08 14:10
Unfortunately I'm missing the logs when the build started... there is a jump in logged data between two twistd.log files

**Comment by jpflori** [comment] 2021-03-02 10:55
This was with 2.10.0 which included #5599 if that is the fix you thought about.
Unfortunately, I miss the log at the time of the issue and it did not reproduce since then, mostly because I diminished the pressure on the latent worker.
I'll make sure to report if the same issue happen again and the logs are available.

**Comment by p12tic** [comment] 2021-03-02 14:58
Thanks, having a confirmation would be great.

**Comment by steven-johnson** [comment] 2021-04-01 21:27
We've been seeing this lately as well, pretty much exclusively on our Windows workers -- apparently some of their network connections are flaky and they end up cancelling themselves, but the master thinks they are still running. (Clicking "Stop" in the web ui just provides an endless "Stopping..." that never actually stops.) Stopping and restarting the master fixes these, but obviously that's not an acceptable fix.

I tried experimenting with shortening keepalive and keepalive_interval but that had no effect. Would love to find a way to fix this as the 'zombie' jobs are a big nuisance. Suggestions welcome; also, if providing logs would help diagnose, please let me know.

**Comment by steven-johnson** [comment] 2021-04-01 22:47
As an example, here's the tail of twisted.log from a windows worker that just had this happen (i.e.: the worker's network flaked for a minute; the web UI for the worker shows the status as "Canceled" but the Workers status page still shows the job as throbbing-yellow-capsule, and the "Stop" button doesn't do anything):

```
2021-04-01 15:20:23-0700 [Broker,client]   using PTY: False
2021-04-01 15:21:03-0700 [-] sending app-level keepalive
2021-04-01 15:21:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:22:03-0700 [-] sending app-level keepalive
2021-04-01 15:22:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:23:03-0700 [-] sending app-level keepalive
2021-04-01 15:23:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:24:03-0700 [-] sending app-level keepalive
2021-04-01 15:24:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:25:03-0700 [-] sending app-level keepalive
2021-04-01 15:25:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:26:03-0700 [-] sending app-level keepalive
2021-04-01 15:26:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:27:03-0700 [-] sending app-level keepalive
2021-04-01 15:27:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:28:03-0700 [-] sending app-level keepalive
2021-04-01 15:28:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:29:03-0700 [-] sending app-level keepalive
2021-04-01 15:29:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:30:03-0700 [-] sending app-level keepalive
2021-04-01 15:30:03-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:30:40-0700 [Broker,client] WorkerForBuilder._ackFailed: WorkerForBuilder.sendUpdate
2021-04-01 15:30:40-0700 [Broker,client] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
        ]

2021-04-01 15:30:40-0700 [Broker,client] WorkerForBuilder._ackFailed: WorkerForBuilder.sendUpdate
2021-04-01 15:30:40-0700 [Broker,client] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
        ]

2021-04-01 15:30:40-0700 [Broker,client] WorkerForBuilder._ackFailed: WorkerForBuilder.sendUpdate
2021-04-01 15:30:40-0700 [Broker,client] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
        ]

2021-04-01 15:30:40-0700 [Broker,client] lost remote step
2021-04-01 15:30:40-0700 [Broker,client] stopCommand: halting current command <buildbot_worker.commands.shell.WorkerShellCommand object at 0x000001EB9F326A60>
2021-04-01 15:30:40-0700 [Broker,client] command interrupted, attempting to kill
2021-04-01 15:30:40-0700 [Broker,client] using TASKKILL PID /F /T to kill pid 6860
2021-04-01 15:30:40-0700 [Broker,client] taskkill'd pid 6860
2021-04-01 15:30:40-0700 [-] Scheduling retry 1 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 2.4276185084175483 seconds.
2021-04-01 15:30:40-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:30:40-0700 [-] command finished with signal None, exit code 1, elapsedTime: 616.420314
2021-04-01 15:30:40-0700 [-] would sendStatus but not .running
2021-04-01 15:30:40-0700 [-] WorkerForBuilder.commandComplete None
2021-04-01 15:30:42-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:03-0700 [-] Scheduling retry 2 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 2.615052142782245 seconds.
2021-04-01 15:31:03-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:06-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:06-0700 [-] Scheduling retry 3 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 3.750537772489395 seconds.
2021-04-01 15:31:06-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:09-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:31-0700 [-] Scheduling retry 4 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 5.930810313276111 seconds.
2021-04-01 15:31:31-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:36-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:36-0700 [-] Scheduling retry 5 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 8.589732518396882 seconds.
2021-04-01 15:31:36-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:45-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:45-0700 [-] Scheduling retry 6 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 11.451941565413545 seconds.
2021-04-01 15:31:45-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:57-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:31:57-0700 [-] Scheduling retry 7 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 17.743804267365913 seconds.
2021-04-01 15:31:57-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:32:14-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:32:35-0700 [-] Scheduling retry 8 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 26.604889648326324 seconds.
2021-04-01 15:32:35-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:33:02-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:33:02-0700 [-] Scheduling retry 9 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 38.491694040154265 seconds.
2021-04-01 15:33:02-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:33:40-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:34:02-0700 [-] Scheduling retry 10 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 58.387752671230466 seconds.
2021-04-01 15:34:02-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:35:00-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:35:00-0700 [-] Scheduling retry 11 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 60.03861585096624 seconds.
2021-04-01 15:35:00-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:36:00-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:36:21-0700 [-] Scheduling retry 12 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 60.74238562665125 seconds.
2021-04-01 15:36:21-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:37:22-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:37:22-0700 [-] Scheduling retry 13 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x000001EB9F082CA0> in 60.9445337721182 seconds.
2021-04-01 15:37:22-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:38:23-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x000001EB9F082820>
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] message from master: attached
2021-04-01 15:38:33-0700 [Broker,client] Connected to buildmaster; worker is ready
2021-04-01 15:38:33-0700 [Broker,client] sending application-level keepalives every 60 seconds
2021-04-01 15:39:33-0700 [-] sending app-level keepalive
2021-04-01 15:39:33-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:40:33-0700 [-] sending app-level keepalive
2021-04-01 15:40:33-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:41:33-0700 [-] sending app-level keepalive
2021-04-01 15:41:33-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:42:33-0700 [-] sending app-level keepalive
2021-04-01 15:42:33-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:43:33-0700 [-] sending app-level keepalive
2021-04-01 15:43:33-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:44:33-0700 [-] sending app-level keepalive
2021-04-01 15:44:33-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:45:33-0700 [-] sending app-level keepalive
2021-04-01 15:45:33-0700 [Broker,client] Master replied to keepalive, everything's fine
2021-04-01 15:46:33-0700 [-] sending app-level keepalive
2021-04-01 15:46:33-0700 [Broker,client] Master replied to keepalive, everything's fine
```

**Comment by steven-johnson** [comment] 2021-05-10 23:44
This is still happening very regularly for us, and it's becoming a big issue -- the stuck workers are 'zombies' that can't get new jobs assigned to them (since the master thinks they are still working). Restarting the master clears this up, but that means interrupting all the other (non-zombie) workers. 

As a stopgap, is there any way to tell the master to flush the work queue of a specific worker without having to stop and restart? That would at least give us a less-bad workaround.

**Comment by p12tic** [comment] 2021-05-11 10:08
> (Do you also want the worker logs?)

Actually yes, I didn't consider that I might not be able to easily tell when the worker disconnected just from master side.

**Comment by tardyp** [comment] 2021-05-11 19:32
> > There is no info in the log on what is the actual origin of this property rendering :-/
> 
> Where would add logging on that?

I think adding some log here might give some more clue of what we are trying to render:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/properties.py#L682

Then, there is this old PR on twisted that is supposed to fix the traceback generation, that was never merged
https://github.com/twisted/twisted/pull/988

Maybe you can try repro with that version of twisted.

> 
> > maybe a simple fix to this is to decide getWorkerInfo should rather return {} if worker is disconnected:
> 
> Are you suggesting I try that out locally? (Happy to do so, just not clear)

If you have a simple repro, I guess this would be worth to see of your build correctly manage to finish.

We can see a bit earlier in the log the connection break:
```log
2021-05-11 11:34:23-0700 [-] RemoteCommand.interrupt <RemoteShellCommand '['ninja', '-C', 'D:/build_bot/worker/llvm-13-x86-64-windows/llvm-build', '-j', '14', 'install']'> [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
	]
2021-05-11 11:34:23-0700 [-] RemoteCommand.disconnect: lost worker
2021-05-11 11:34:23-0700 [Broker,2,104.132.0.72] Got workerinfo from 'win-worker-1'
2021-05-11 11:34:23-0700 [-] bot attached
2021-05-11 11:34:23-0700 [Broker,2,104.132.0.72] Worker win-worker-1 attached to llvm-12-x86-64-windows/win-worker-1
```

We can see here that the master detects connection lost and the worker reconnects in the same second.

Franckly I am not sure so much time shall be spent in making buildbot fail properly for such network flakyness. That time would be better spent in fixing the flackyness IMHO.

The pb protocol is not resistant to network flakyness, this is a shame, but too hard to fix at that point.
I hope we can fix this issue with the next protocol @mokibit  is working on.

**Comment by p12tic** [comment] 2021-05-11 21:08
> Franckly I am not sure so much time shall be spent in making buildbot fail properly for such network flakyness

I think it's worth it. There will always be weird environments with plenty of things being unreliable. Buildbot should handle them properly.

Regarding the failure, I suspect that the cause may be rendering of the build properties that is done before each step in `setBuildProperties()`.

@steven-johnson I think you can apply the patch suggested by Pierre as an interim solution. It may not help though. In the mean time I will look for a proper solution to shut down the master-side build completely as soon as worker disconnects.

**Comment by p12tic** [comment] 2021-05-14 01:51
@steven-johnson Check out https://github.com/buildbot/buildbot/pull/6051, this should fix at least some of the problems you're seeing as I was able to reproduce exact same logs in an integration test.

**Comment by p12tic** [comment] 2021-05-14 11:48
Thinking about this a little bit more, the fix in #6051 is essentially an upgraded version of what Pierre suggested and what you've tested already. Since this will be merged to Buildbot proper anyway, it would be great if you could test it and then if issues still happen, create another set of master/worker logs that I could look into. The errors will be different in that case, so without the logs it would be difficult to understand what problem is happening.

**Comment by steven-johnson** [comment] 2021-05-14 16:22
Wow, fantastic, thanks!

https://github.com/buildbot/buildbot/pull/6051 says that https://github.com/buildbot/buildbot/pull/6052 also needs to land for it to be stable -- is that just for internal tests, or do I need to patch them both in to try it locally?

**Comment by steven-johnson** [comment] 2021-05-14 20:06
So far this looks like a huge improvement in reliability for us.

**Closed** 2021-05-15 05:39 UTC
Labels: bug
