### ISSUE TITLE
FakeTransport error while starting buildbot.

### ISSUE THREAD

**Issue by alexreinking** [buildbot/buildbot#5706] opened 2020-12-21 19:52 UTC
I'm trying to understand why I'm getting the following error, even though the master seems to start and run normally. Googling for this message was fruitless. I'm using buildbot 2.9.3 and Twisted 20.3.0 (both latest). Do I need to downgrade Twisted?

```
(venv) alex@solitude:~/build_bot$ buildbot start master
Following twistd.log until startup finished..
Unhandled Error
Traceback (most recent call last):
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/internet/process.py", line 252, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/internet/process.py", line 256, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/internet/process.py", line 922, in childDataReceived
    self.proto.childDataReceived(name, data)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/internet/protocol.py", line 640, in childDataReceived
    self.outReceived(data)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/buildbot/scripts/logwatcher.py", line 49, in outReceived
    self.lw.dataReceived(data)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/protocols/basic.py", line 452, in dataReceived
    return self.lineLengthExceeded(line)
  File "/home/alex/build_bot/venv/lib/python3.7/site-packages/twisted/protocols/basic.py", line 484, in lineLengthExceeded
    return self.transport.loseConnection()
builtins.AttributeError: 'FakeTransport' object has no attribute 'loseConnection'

The buildmaster took more than 10.0 seconds to start, so we were unable to
confirm that it started correctly. Please 'tail twistd.log' and look for a line
that says 'BuildMaster is running' to verify correct startup.
```

_Originally posted by @alexreinking in https://github.com/buildbot/buildbot/discussions/5702_

**Comment by p12tic** [comment] 2020-12-22 05:40
Thanks for the bug report. I haven't yet looked deeply into Twisted, but it seems that we were relying on their non-documented behavior, which has changed.

The error is harmless.

**Comment by alexreinking** [comment] 2020-12-22 20:27
> Thanks for the bug report. I haven't yet looked deeply into Twisted, but it seems that we were relying on their non-documented behavior, which has changed.

Do you know which is the most recent version that does not display this error?

> The error is harmless.

Good to know, thanks.

**Comment by alexreinking** [comment] 2020-12-22 20:32
> Do you know which is the most recent version that does not display this error?

Through trial and error, it appears it is 17.9.0

**Comment by p12tic** [comment] 2020-12-26 15:42
@alexreinking Could you check your twistd.log again? It seems that the error is caused by lines longer than 16 kilobytes. This may be a symptom of another bug. The long line handling has been fixed in #5710.

**Closed** 2020-12-26 17:37 UTC

**Comment by alexreinking** [comment] 2020-12-26 20:21
That appears to have been the issue. We were printing a long JSON object from GitHub that exceeded the line length.

**Comment by p12tic** [comment] 2020-12-26 21:59
> We were printing a long JSON object from GitHub

Alright, the long lines were an expected behavior. Thanks for looking into this.

**Comment by alexreinking** [comment] 2020-12-26 23:41
> Alright, the long lines were an expected behavior. Thanks for looking into this.

Of course! Happy to be of service.
