### ISSUE TITLE
tried to complete 1 buildrequests, but only completed 0

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3472] opened 2017-07-26 03:45 UTC
This happens when **3** changes comes at a time. The first one got handled perfectly. Problem is the 2nd and 3rd change when the 2nd change was merged to 3rd and a `NotClaimedError` was raised. I use Perforce as CVS.
and log is:
```
2017-07-26 11:39:39+0800 [-] added change with revision 98 to database
2017-07-26 11:39:59+0800 [-] added buildset 324 to database
2017-07-26 11:39:59+0800 [-] added change with revision 99 to database
2017-07-26 11:40:19+0800 [-] starting build <Build runtests number:None results:success> using worker <WorkerForBuilder builder=u'runtests' worker=u'example-worker' state=AVAILABLE>
2017-07-26 11:40:19+0800 [-] <Build runtests number:None results:success>.startBuild
2017-07-26 11:40:21+0800 [-] added buildset 325 to database
2017-07-26 11:40:22+0800 [-] acquireLocks(worker <Worker u'example-worker'>, locks [])
2017-07-26 11:40:22+0800 [-] starting build <Build runtests number:295 results:success>.. pinging the worker <WorkerForBuilder builder=u'runtests' worker=u'example-worker' state=BUILDING>
2017-07-26 11:40:22+0800 [-] sending ping
2017-07-26 11:40:22+0800 [Broker,0,127.0.0.1] ping finished: success
// Blabla...OMIT a lot P4 sync command
2017-07-26 11:40:28+0800 [-]  step 'p4' complete: success (None)
2017-07-26 11:40:28+0800 [-]  <Build runtests number:295 results:success>: build finished
2017-07-26 11:40:28+0800 [-] releaseLocks(<Worker u'example-worker'>): []
2017-07-26 11:40:29+0800 [-] tried to complete 1 buildrequests, but only completed 0
2017-07-26 11:40:29+0800 [-] Got fatal Exception on DB
	Traceback (most recent call last):
	Failure: buildbot.db.buildrequests.NotClaimedError: 
```

**Comment by lancelodliu** [comment] 2017-07-26 08:19
I found the `NotClaimedError` is excepted at data/buildrequest.py:230 as below.
```
    @base.updateMethod
    @defer.inlineCallbacks
    def completeBuildRequests(self, brids, results, complete_at=None,
                              _reactor=reactor):
        assert results != RETRY, "a buildrequest cannot be completed with a retry status!"
        if not brids:
            # empty buildrequest list. No need to call db API
            defer.returnValue(True)
        try:
            yield self.master.db.buildrequests.completeBuildRequests(
                brids,
                results,
                complete_at=complete_at,
                _reactor=_reactor)
        except NotClaimedError:
            # the db layer returned a NotClaimedError exception, usually
            # because one of the buildrequests has been claimed by another
            # master
            defer.returnValue(False)
        yield self.generateEvent(brids, "complete")
```
But I only start **one** master.

**Comment by tardyp** [comment] 2017-07-26 09:17
which version of buildbot is it?

looks like it is similar to #3406 fixed it https://github.com/buildbot/buildbot/pull/3411

**Comment by lancelodliu** [comment] 2017-07-26 09:22
Buildbot version: 0.9.9.post2
Twisted version: 16.6.0

**Comment by tardyp** [comment] 2017-07-26 09:28
looks like a new bug then.

Can you please post the results of those rest api when this happend to understand what happen?

https://xx/api/v2/builds?limit=10
https://xx/api/v2/buildrequests?limit=10
https://xx/api/v2/buildsets?limit=10

**Comment by lancelodliu** [comment] 2017-07-26 09:38
https://xx/api/v2/builds?limit=10
```
{
  "builds": [
    {
      "builderid": 4, 
      "buildid": 1, 
      "buildrequestid": 1, 
      "complete": true, 
      "complete_at": 1501058119, 
      "masterid": 1, 
      "number": 1, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501058110, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 2, 
      "buildrequestid": 3, 
      "complete": true, 
      "complete_at": 1501058127, 
      "masterid": 1, 
      "number": 2, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501058119, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 3, 
      "buildrequestid": 4, 
      "complete": true, 
      "complete_at": 1501058179, 
      "masterid": 1, 
      "number": 3, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501058170, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 4, 
      "buildrequestid": 6, 
      "complete": true, 
      "complete_at": 1501058189, 
      "masterid": 1, 
      "number": 4, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501058180, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 5, 
      "buildrequestid": 8, 
      "complete": true, 
      "complete_at": 1501058199, 
      "masterid": 1, 
      "number": 5, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501058190, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 6, 
      "buildrequestid": 9, 
      "complete": true, 
      "complete_at": 1501058394, 
      "masterid": 1, 
      "number": 6, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501058368, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 7, 
      "buildrequestid": 11, 
      "complete": true, 
      "complete_at": 1501058483, 
      "masterid": 1, 
      "number": 7, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501058394, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 8, 
      "buildrequestid": 12, 
      "complete": true, 
      "complete_at": 1501059032, 
      "masterid": 1, 
      "number": 8, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501059024, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 9, 
      "buildrequestid": 13, 
      "complete": true, 
      "complete_at": 1501059048, 
      "masterid": 1, 
      "number": 9, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501059040, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 10, 
      "buildrequestid": 14, 
      "complete": true, 
      "complete_at": 1501059056, 
      "masterid": 1, 
      "number": 10, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501059048, 
      "state_string": "build successful", 
      "workerid": 3
    }
  ], 
  "meta": {
    "total": 10
  }
}
```
https://xx/api/v2/buildrequests?limit=10
```
{
  "buildrequests": [
    {
      "builderid": 4, 
      "buildrequestid": 1, 
      "buildsetid": 1, 
      "claimed": true, 
      "claimed_at": 1501058110, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058110, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501058109, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 2, 
      "buildsetid": 2, 
      "claimed": true, 
      "claimed_at": 1501058114, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058114, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501058109, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 3, 
      "buildsetid": 3, 
      "claimed": true, 
      "claimed_at": 1501058119, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058127, 
      "priority": 0, 
      "results": 0, 
      "submitted_at": 1501058112, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 4, 
      "buildsetid": 4, 
      "claimed": true, 
      "claimed_at": 1501058170, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058170, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501058169, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 5, 
      "buildsetid": 5, 
      "claimed": true, 
      "claimed_at": 1501058174, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058174, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501058169, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 6, 
      "buildsetid": 6, 
      "claimed": true, 
      "claimed_at": 1501058180, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058189, 
      "priority": 0, 
      "results": 0, 
      "submitted_at": 1501058172, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 7, 
      "buildsetid": 7, 
      "claimed": true, 
      "claimed_at": 1501058189, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058189, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501058185, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 8, 
      "buildsetid": 8, 
      "claimed": true, 
      "claimed_at": 1501058190, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058199, 
      "priority": 0, 
      "results": 0, 
      "submitted_at": 1501058187, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 9, 
      "buildsetid": 9, 
      "claimed": true, 
      "claimed_at": 1501058368, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058384, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501058364, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 10, 
      "buildsetid": 10, 
      "claimed": true, 
      "claimed_at": 1501058388, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501058388, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501058364, 
      "waited_for": false
    }
  ], 
  "meta": {
    "total": 10
  }
}
```
https://xx/api/v2/buildsets?limit=10
```
{
  "buildsets": [
    {
      "bsid": 1, 
      "complete": true, 
      "complete_at": 1501058111, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058108, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "167", 
          "ssid": 1
        }
      ], 
      "submitted_at": 1501058109
    }, 
    {
      "bsid": 2, 
      "complete": true, 
      "complete_at": 1501058115, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058109, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "168", 
          "ssid": 2
        }
      ], 
      "submitted_at": 1501058109
    }, 
    {
      "bsid": 3, 
      "complete": true, 
      "complete_at": 1501058127, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058110, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "169", 
          "ssid": 3
        }
      ], 
      "submitted_at": 1501058112
    }, 
    {
      "bsid": 4, 
      "complete": true, 
      "complete_at": 1501058171, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058168, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "170", 
          "ssid": 4
        }
      ], 
      "submitted_at": 1501058169
    }, 
    {
      "bsid": 5, 
      "complete": true, 
      "complete_at": 1501058176, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058169, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "171", 
          "ssid": 5
        }
      ], 
      "submitted_at": 1501058169
    }, 
    {
      "bsid": 6, 
      "complete": true, 
      "complete_at": 1501058190, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058170, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "172", 
          "ssid": 6
        }
      ], 
      "submitted_at": 1501058172
    }, 
    {
      "bsid": 7, 
      "complete": true, 
      "complete_at": 1501058190, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058184, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "173", 
          "ssid": 7
        }
      ], 
      "submitted_at": 1501058185
    }, 
    {
      "bsid": 8, 
      "complete": true, 
      "complete_at": 1501058199, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058185, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "174", 
          "ssid": 8
        }
      ], 
      "submitted_at": 1501058187
    }, 
    {
      "bsid": 9, 
      "complete": true, 
      "complete_at": 1501058386, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058363, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "175", 
          "ssid": 9
        }
      ], 
      "submitted_at": 1501058364
    }, 
    {
      "bsid": 10, 
      "complete": true, 
      "complete_at": 1501058390, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501058364, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "176", 
          "ssid": 10
        }
      ], 
      "submitted_at": 1501058364
    }
  ], 
  "meta": {
    "total": 10
  }
}
```

**Comment by tardyp** [comment] 2017-07-26 09:50
sorry. shall be:

https://xx/api/v2/builds?limit=10&order=-buildid
https://xx/api/v2/buildrequests?limit=10&order=-buildrequestid
https://xx/api/v2/buildsets?limit=10&order=-buildsetid

**Comment by lancelodliu** [comment] 2017-07-26 09:50
You can reproduce this as below:

1. Use polling source(I use Perforce) 
2. Set the poll interval a bit larger like 15 seconds.
3. Submit 3 commits at a time(1~2 seconds, just make sure they are pushed during the poll interval).
4. Wait

P.S.: If you push 5 commints #1-#5, then the first will raise the Error and there will be only 3 builds to be done which consists of #1, #2-#3 and #4-#5 seperately.

**Comment by tardyp** [comment] 2017-07-26 09:51
just to confirm, I believe you have configured the buildrequest collapser, right?

**Comment by lancelodliu** [comment] 2017-07-26 09:53
**First**
```
{
  "builds": [
    {
      "builderid": 4, 
      "buildid": 18, 
      "buildrequestid": 26, 
      "complete": true, 
      "complete_at": 1501061524, 
      "masterid": 1, 
      "number": 18, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501061516, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 17, 
      "buildrequestid": 24, 
      "complete": true, 
      "complete_at": 1501061515, 
      "masterid": 1, 
      "number": 17, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501061507, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 16, 
      "buildrequestid": 23, 
      "complete": true, 
      "complete_at": 1501061368, 
      "masterid": 1, 
      "number": 16, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501061360, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 15, 
      "buildrequestid": 21, 
      "complete": true, 
      "complete_at": 1501061359, 
      "masterid": 1, 
      "number": 15, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501061351, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 14, 
      "buildrequestid": 20, 
      "complete": true, 
      "complete_at": 1501061236, 
      "masterid": 1, 
      "number": 14, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501061228, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 13, 
      "buildrequestid": 18, 
      "complete": true, 
      "complete_at": 1501061227, 
      "masterid": 1, 
      "number": 13, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501061211, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 12, 
      "buildrequestid": 17, 
      "complete": true, 
      "complete_at": 1501059636, 
      "masterid": 1, 
      "number": 12, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501059628, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 11, 
      "buildrequestid": 15, 
      "complete": true, 
      "complete_at": 1501059628, 
      "masterid": 1, 
      "number": 11, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501059611, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 10, 
      "buildrequestid": 14, 
      "complete": true, 
      "complete_at": 1501059056, 
      "masterid": 1, 
      "number": 10, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501059048, 
      "state_string": "build successful", 
      "workerid": 3
    }, 
    {
      "builderid": 4, 
      "buildid": 9, 
      "buildrequestid": 13, 
      "complete": true, 
      "complete_at": 1501059048, 
      "masterid": 1, 
      "number": 9, 
      "properties": {}, 
      "results": 0, 
      "started_at": 1501059040, 
      "state_string": "build successful", 
      "workerid": 3
    }
  ], 
  "meta": {
    "total": 10
  }
}
```
**Second**
```
{
  "buildrequests": [
    {
      "builderid": 4, 
      "buildrequestid": 26, 
      "buildsetid": 26, 
      "claimed": true, 
      "claimed_at": 1501061516, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501061524, 
      "priority": 0, 
      "results": 0, 
      "submitted_at": 1501061509, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 25, 
      "buildsetid": 25, 
      "claimed": true, 
      "claimed_at": 1501061510, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501061511, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501061506, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 24, 
      "buildsetid": 24, 
      "claimed": true, 
      "claimed_at": 1501061507, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501061507, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501061506, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 23, 
      "buildsetid": 23, 
      "claimed": true, 
      "claimed_at": 1501061360, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501061368, 
      "priority": 0, 
      "results": 0, 
      "submitted_at": 1501061352, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 22, 
      "buildsetid": 22, 
      "claimed": true, 
      "claimed_at": 1501061354, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501061354, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501061350, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 21, 
      "buildsetid": 21, 
      "claimed": true, 
      "claimed_at": 1501061351, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501061351, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501061349, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 20, 
      "buildsetid": 20, 
      "claimed": true, 
      "claimed_at": 1501061228, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501061236, 
      "priority": 0, 
      "results": 0, 
      "submitted_at": 1501061218, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 19, 
      "buildsetid": 19, 
      "claimed": true, 
      "claimed_at": 1501061221, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501061222, 
      "priority": 0, 
      "results": 3, 
      "submitted_at": 1501061211, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 18, 
      "buildsetid": 18, 
      "claimed": true, 
      "claimed_at": 1501061211, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501061228, 
      "priority": 0, 
      "results": 0, 
      "submitted_at": 1501061184, 
      "waited_for": false
    }, 
    {
      "builderid": 4, 
      "buildrequestid": 17, 
      "buildsetid": 17, 
      "claimed": true, 
      "claimed_at": 1501059628, 
      "claimed_by_masterid": 1, 
      "complete": true, 
      "complete_at": 1501059637, 
      "priority": 0, 
      "results": 0, 
      "submitted_at": 1501059616, 
      "waited_for": false
    }
  ], 
  "meta": {
    "total": 10
  }
}
```
**Third**, http://localhost:8020/api/v2/buildsets?limit=10&order=-bsid
```
{
  "buildsets": [
    {
      "bsid": 26, 
      "complete": true, 
      "complete_at": 1501061524, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501061507, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "192", 
          "ssid": 26
        }
      ], 
      "submitted_at": 1501061509
    }, 
    {
      "bsid": 25, 
      "complete": true, 
      "complete_at": 1501061512, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501061506, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "191", 
          "ssid": 25
        }
      ], 
      "submitted_at": 1501061506
    }, 
    {
      "bsid": 24, 
      "complete": true, 
      "complete_at": 1501061508, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501061506, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "190", 
          "ssid": 24
        }
      ], 
      "submitted_at": 1501061506
    }, 
    {
      "bsid": 23, 
      "complete": true, 
      "complete_at": 1501061368, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501061350, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "189", 
          "ssid": 23
        }
      ], 
      "submitted_at": 1501061352
    }, 
    {
      "bsid": 22, 
      "complete": true, 
      "complete_at": 1501061356, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501061349, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "188", 
          "ssid": 22
        }
      ], 
      "submitted_at": 1501061350
    }, 
    {
      "bsid": 21, 
      "complete": true, 
      "complete_at": 1501061352, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501061349, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "187", 
          "ssid": 21
        }
      ], 
      "submitted_at": 1501061349
    }, 
    {
      "bsid": 20, 
      "complete": true, 
      "complete_at": 1501061237, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501061211, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "186", 
          "ssid": 20
        }
      ], 
      "submitted_at": 1501061218
    }, 
    {
      "bsid": 19, 
      "complete": true, 
      "complete_at": 1501061222, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501061211, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "185", 
          "ssid": 19
        }
      ], 
      "submitted_at": 1501061211
    }, 
    {
      "bsid": 18, 
      "complete": true, 
      "complete_at": 1501061228, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501061184, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "184", 
          "ssid": 18
        }
      ], 
      "submitted_at": 1501061184
    }, 
    {
      "bsid": 17, 
      "complete": true, 
      "complete_at": 1501059637, 
      "external_idstring": null, 
      "parent_buildid": null, 
      "parent_relationship": null, 
      "reason": "The SingleBranchScheduler scheduler named 'all' triggered this build", 
      "results": 0, 
      "sourcestamps": [
        {
          "branch": null, 
          "codebase": "", 
          "created_at": 1501059611, 
          "patch": null, 
          "project": "Test", 
          "repository": "", 
          "revision": "183", 
          "ssid": 17
        }
      ], 
      "submitted_at": 1501059616
    }
  ], 
  "meta": {
    "total": 10
  }
}
```

**Comment by lancelodliu** [comment] 2017-07-26 09:54
No, I configure it as the tutorial.
```
c['builders'] = []
c['builders'].append(
    util.BuilderConfig(name="runtests",
      workernames=["example-worker"],
      factory=factory))
```

**Comment by lancelodliu** [comment] 2017-07-26 10:34
Should I set `collapseRequests` to `False` explicitly to disable this function?

**Comment by tardyp** [comment] 2017-07-26 10:58
for the last set of builds that you sent, what is the exact error message?
In the original error, it refers build 295, which is not part of your dump.

**Comment by lancelodliu** [comment] 2017-07-26 11:01
```
2017-07-26 17:31:46+0800 [-] added change with revision 190 to database
2017-07-26 17:31:46+0800 [-] added buildset 24 to database
2017-07-26 17:31:46+0800 [-] added change with revision 191 to database
2017-07-26 17:31:47+0800 [-] added change with revision 192 to database
2017-07-26 17:31:47+0800 [-] starting build <Build runtests number:None results:success> using worker <WorkerForBuilder builder=u'runtests' worker=u'example-worker' state=AVAILABLE>
2017-07-26 17:31:47+0800 [-] <Build runtests number:None results:success>.startBuild
2017-07-26 17:31:49+0800 [-] added buildset 25 to database
2017-07-26 17:31:49+0800 [-] acquireLocks(worker <Worker u'example-worker'>, locks [])
2017-07-26 17:31:50+0800 [-] starting build <Build runtests number:17 results:success>.. pinging the worker <WorkerForBuilder builder=u'runtests' worker=u'example-worker' state=BUILDING>
2017-07-26 17:31:50+0800 [-] sending ping
2017-07-26 17:31:50+0800 [Broker,0,127.0.0.1] ping finished: success
# blabla...
2017-07-26 17:31:53+0800 [-] added buildset 26 to database
2017-07-26 17:31:54+0800 [-] releaseLocks(P4(p4passwd='liuyujie', p4port='localhost:1666', mode='incremental', p4user='lancelodliu', p4base='//depot')): []
2017-07-26 17:31:55+0800 [-]  step 'p4' complete: success (None)
2017-07-26 17:31:55+0800 [-]  <Build runtests number:17 results:success>: build finished
2017-07-26 17:31:56+0800 [-] releaseLocks(<Worker u'example-worker'>): []
2017-07-26 17:31:56+0800 [-] tried to complete 1 buildrequests, but only completed 0
2017-07-26 17:31:56+0800 [-] Got fatal Exception on DB
	Traceback (most recent call last):
	Failure: buildbot.db.buildrequests.NotClaimedError: 
```

**Comment by tardyp** [comment] 2017-07-26 11:09
So build 17 is associated with buildrequest 24, which is marked skipped in the DB, which means it has been collapsed. So there might be a race to claim between the collapser and the distributor.
If the same master is claiming the same buildrequest (one for collapser, one for distributor) maybe our race condition mechanism do not work..

**Comment by lancelodliu** [comment] 2017-07-26 11:11
Maybe. Disabling the collapse solves this anyway.

**Comment by tardyp** [comment] 2017-07-26 11:15
You can also use treestabletimer in order to force only one build for you
single push

Le mer. 26 juil. 2017 13:11, lancelodliu <notifications@github.com> a
écrit :

**Comment by lancelodliu** [comment] 2017-07-26 14:23
I already set `treeStableTimer` to `None` to start a separate build immediately for each `Change`.

**Comment by aj062** [comment] 2017-10-04 21:12
I am also seeing this issue multiple times every day. I have many builders using collapseRequests and I can't disable collapseRequests on all of them. Is there any fix/workaround for this issue?

I have not configured treestabletimer. Will treestabletimer help in this case?

**Comment by tardyp** [comment] 2017-10-05 07:37
This should be fixed in next release..

**Comment by tardyp** [comment] 2017-10-05 07:40
duplicate of #3591

**Closed by tardyp** 2017-10-05 07:40 UTC
Labels: bug
