### ISSUE TITLE
Can't just send a buildbot URL to someone without explaining what it refers to

### ISSUE THREAD

**Issue by dankegel** [buildbot/buildbot#4342] opened 2018-09-26 16:29 UTC
Use case:
  I want to tell somebody about a build
  I send them a URL to a buildbot page via slack
Problem:
  With numerical references in the URL rather than symbolic ones, it's not obvious what the URL means
  Users feel uncomfortable and have to think harder

#3465 describes one aspect of this, but there are others, e.g. http://nine.buildbot.net/#/workers/11 is not as readable as http://nine.buildbot.net/#/workers/buildbot-linux4 (the latter does not work yet)

**Comment by aj062** [comment] 2018-09-30 13:29
Similar issues: https://github.com/buildbot/buildbot/issues/3465 https://github.com/buildbot/buildbot/issues/3407#issuecomment-317241005

**Comment by tardyp** [comment] 2018-10-01 06:09
duplicate of #3465

**Closed by tardyp** 2018-10-01 06:09 UTC

**Comment by dankegel** [comment] 2018-10-01 12:52
Sorry, 3465 seemed specific to builders.

**Comment by tardyp** [comment] 2018-10-01 12:54
We may add another for workers.
