### ISSUE TITLE
buildbot_windows_service.exe issue

### ISSUE THREAD

**Issue by vx-i** [buildbot/buildbot#5349] opened 2020-06-13 15:01 UTC
Hi, I installed Buildbot on Windows Server 2016 (Version 1607). Before Buildbot installation I did this steps:

- Installed Python version 3.8.3 on C:\Python38
- Updated pip
- Installed Pywin32 via pip
- Executed pywin32_postinstall script

When I execute buildbot from command line

`buildbot start D:\Buildbot\master`

everything is fine. I can reach http interface, run jobs, etc. But if I try to install and run windows service, buildbot fails. What can I do to get more details?

---
Buildbot version: 2.8.1
Twisted version: 20.3.0
Pywin32 version: 228

`PS C:\Windows\system32> buildbot_windows_service.exe debug D:\Buildbot\master\`
Debugging service BuildBot - press Ctrl+C to stop.
Info 0x40001002 - The BuildBot service has started (BuildBot).
Info 0x400000FF - Starting BuildBot in directory 'D:\Buildbot\master'
Exception in thread Thread-1:
Traceback (most recent call last): File "c:\python38\lib\site-packages\buildbot\scripts\windows_service.py", line 402, in redirectCaptureThread
Error 0xC0000003 - The instance's SvcRun() method failed
Error getting traceback - traceback.print_exception() failed
"(null): (null)"

---

There is an issue with pipes, but if I run pywin32 demo services, all services starts and runs perfectly.  

I would be very happy about your help.

**Comment by p12tic** [comment] 2020-06-13 16:25
@vx-i: Thanks for the bug report. I think this is already fixed, see #5345. Could you please test the one-line fix outlined in that PR? If it works for you too, then I'll release BuildBot 2.8.2 with that fix.

**Comment by vx-i** [comment] 2020-06-13 16:39
@p12tic: Yes, it's working. Many thanks.

**Comment by p12tic** [comment] 2020-06-14 19:30
The fix is now in BuildBot 2.8.2, closing.

The issue itself is duplicate of #5344.

**Closed by p12tic** 2020-06-14 19:30 UTC
