### ISSUE TITLE
Regression: steps.Git fails in version 1.4.

### ISSUE THREAD

**Issue by jakobhu** [buildbot/buildbot#4337] opened 2018-09-23 08:19 UTC
When using buildbot version 1.4 i see the following failure from a git buildstep:

mkdir: Permission denied: /home/jakob/Projects/ci/master/.build.buildbotprogram finished with exit code 13

This path does not exist on the worker machine - but is a valid path on the master machine.
The worker is requested to create a path which is in fact a host path - and the git buildstep fails.
I don't see this problem when using buildbot 1.3

**Comment by jakobhu** [comment] 2018-09-23 08:33
Note: If i create the folder '/home/jakob/Projects/ci/master/' on the worker (with write permissions) - the build proceeds as expected.

**Comment by tardyp** [comment] 2018-09-23 08:41
dupe of #4316

**Closed by tardyp** 2018-09-23 08:41 UTC
