### ISSUE TITLE
The buildbot server cannot monitor the code change information on Gerrit(buildbot服务端监控不到gerrit上代码变更信息)

### ISSUE THREAD

**Issue by WorkerToBoss** [buildbot/buildbot#5772] opened 2021-01-26 07:40 UTC
Recently, the buildbot client suddenly can't monitor the code change information of one of our projects. Other projects can be monitored normally, but our own projects can't be monitored at all. The account permissions used can monitor everyone. Have you encountered such problems? Thank you.

最近buildbot客户端突然监控不到我们一个项目的代码变更信息了，其他项目的都可以正常监控到，唯独我们自己的项目一点也监控不到，使用的账户权限是可以监控所有人的，请问你们有没有遇到这类问题？求解答，谢谢。

**Comment by p12tic** [comment] 2021-01-27 18:55
Is there anything unusual in the logs?

**Comment by p12tic** [comment] 2021-03-01 21:14
Without any extra information I'm afraid it won't be possible to figure out the cause of the bug and fix it. Thus I'm closing the bug report. Please reopen if you have any additional information. Thanks!

**Closed by p12tic** 2021-03-01 21:14 UTC
