### ISSUE TITLE
Gitpoller stops polling for changes after a while

### ISSUE THREAD

**Issue by sabgit** [buildbot/buildbot#4068] opened 2018-04-26 18:33 UTC
We have a buildbot master (running version 0.9.15.post1) with multiple gitpollers polling changes from the master branch of multiple (7) repositories. The gitpollers are configured to poll for changes every 30 second. After the initial start up, I can see from the log that they poll for changes from all Git repositories and schedule builds for changes properly:

`
2018-04-19 08:44:51-0400 [-] gitpoller: processing changes from "ssh://..../repo1.git"
2018-04-19 08:44:51-0400 [-] gitpoller: processing changes from "ssh://..../repo2.git"
...

2018-04-20 15:24:52-0400 [-] gitpoller: processing changes from "ssh://.../repo1.git"
2018-04-20 15:24:52-0400 [-] gitpoller: processing 4 changes: [u'0a48b38aa9c53029f28f670a957fb784b4d6ae3b', u'c5bddb4d98b79570a50ad837b137d39b683145d8', u'44d1c0352ef6879fc62126db5eb7ee4c097565fb', u'46d053d54dfc14fd72b9132240f321ceb1cf4c83'] from "ssh://.../repo1.git" branch "master"
2018-04-20 15:24:52-0400 [-] added change with revision 0a48b38aa9c53029f28f670a957fb784b4d6ae3b to database
2018-04-20 15:24:52-0400 [-] added change with revision c5bddb4d98b79570a50ad837b137d39b683145d8 to database
2018-04-20 15:24:52-0400 [-] added change with revision 44d1c0352ef6879fc62126db5eb7ee4c097565fb to database
2018-04-20 15:24:52-0400 [-] added change with revision 46d053d54dfc14fd72b9132240f321ceb1cf4c83 to database
...
2018-04-20 15:25:52-0400 [-] added buildset 1044 to database
2018-04-20 15:25:52-0400 [-] starting build <Build ..... number:None results:success> using worker <WorkerForBuilder builder=u'....' worker=u'....' state=AVAILABLE>
2018-04-20 15:25:52-0400 [-] <Build .... number:None results:success>.startBuild
`
After a while though we notice that the gitpollers stop polling so the merges to master branches no more trigger a build. After restarting the build master however, it picks up the changes and schedules builds. 

There is not an obvious error in the twistd.log that would give a clue. 

Can you please advise on how to go about tracking down this issue?

We are using buildbot version 0.9.15.post1

**Comment by aj062** [comment] 2018-04-28 03:53
Similar issue: https://github.com/buildbot/buildbot/issues/3646

**Comment by seankelly** [comment] 2018-05-19 01:36
Per the linked issue, are there any stuck git processes?

**Comment by sabgit** [comment] 2018-05-21 15:09
I increased the polling interval from 30 seconds to 180 to avoid hitting the issue and it does not happen anymore so my guess is this might be related to some kind of synchronization issue when there are multiple pollers running in a short window of time.

**Comment by sabgit** [comment] 2018-11-16 09:30
this has happened again, any help/direction is appreciated.

**Comment by p12tic** [comment] 2021-09-05 02:53
If the issue is stuck process, this has been fixed in db93fb275189ee63a7f1017f17846d01d1ad95a8 which landed to Buildbot 3.2.0.

**Closed by p12tic** 2021-09-05 02:53 UTC
Labels: changesource
