### ISSUE TITLE
exceptions.UnicodeDecodeError: invalid start byte

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3448] opened 2017-07-17 16:05 UTC
I am noticing this error in twisted.log every time I try to open console view (and the console view doesn't open, keeps showing loading image).

2017-07-17 08:58:04-0700 [-] while handling API request
	Traceback (most recent call last):
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1355, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/lib/python2.7/site-packages/buildbot/www/rest.py", line 453, in renderRest
	    request.write(data)
	  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
	    self.gen.throw(type, value, traceback)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/buildbot/www/rest.py", line 141, in handleErrors
	    yield
	  File "/usr/lib/python2.7/site-packages/buildbot/www/rest.py", line 444, in renderRest
	    sort_keys=True, separators=(',', ':'))
	  File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
	    sort_keys=sort_keys, **kw).encode(obj)
	  File "/usr/lib64/python2.7/json/encoder.py", line 209, in encode
	    chunks = list(chunks)
	  File "/usr/lib64/python2.7/json/encoder.py", line 434, in _iterencode
	    for chunk in _iterencode_dict(o, _current_indent_level):
	  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
	    for chunk in chunks:
	  File "/usr/lib64/python2.7/json/encoder.py", line 332, in _iterencode_list
	    for chunk in chunks:
	  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
	    for chunk in chunks:
	  File "/usr/lib64/python2.7/json/encoder.py", line 332, in _iterencode_list
	    for chunk in chunks:
	  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
	    for chunk in chunks:
	  File "/usr/lib64/python2.7/json/encoder.py", line 390, in _iterencode_dict
	    yield _encoder(value)
	exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 15867: invalid start byte

<img width="654" alt="console_view_loading" src="https://user-images.githubusercontent.com/3098702/28277397-b7c9fbec-6ace-11e7-90b4-abf3eb39a1bc.png">

**Comment by tardyp** [comment] 2017-07-17 16:40
Could you please tell which REST API fails (by looking at browser developer console)

**Comment by aakashja** [comment] 2017-07-18 05:25
Console shows: "https://localhost/api/v2/buildsets?limit=200&order=-submitted_at  Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500)"

Manually opening the url (or opening https://localhost/api/v2/buildsets) gives a json with key "error" and value containing contents of a large patch (which was misformatted).

Note that this buildbot is having various try bots.

**Comment by tardyp** [comment] 2017-07-18 07:08
```<rodrigc> what is causing Aakash Jain's unicode decode errors?
09:05:23 T<@tardyp> rodrigc: looks like a bad patch sneaked in via the try scheduler
09:06:31 R<rodrigc> some binary characters in the patch?
09:06:38 T<@tardyp> someone must have sent a patch with some special chars, but it was not correctly encoded
```

**Comment by aakashja** [comment] 2017-07-18 15:59
Thanks. I identified the bad patch. I have two questions:

1) How can I recover from it? Can I run any buildbot command or postgres queries to delete the bad patch from db?

2) Can we try to ensure this doesn't happen again by adding required checks in buildbot? I am happy to provide any debugging data.

**Comment by tardyp** [comment] 2017-07-18 16:37
1. you may try to delete the patch from the db.

2. this is something that we discussed with rodrigc on IRC, we have to fix it eventually, by adding a unit test on the try scheduler to try and create a patch containing some binary chars.

**Comment by rodrigc** [comment] 2018-04-11 14:00
Maybe related to https://github.com/buildbot/buildbot/pull/4038

**Comment by rodrigc** [comment] 2019-01-19 06:13
Duplicate of #4038

**Closed by rodrigc** 2019-01-19 06:13 UTC
Labels: bug, bytes, easy, good first issue
