### ISSUE TITLE
buildbot reconfig failed with error: maximum recursion depth exceeded 

### ISSUE THREAD

**Issue by jain-aakash** [buildbot/buildbot#6341] opened 2022-01-20 17:20 UTC
buildbot reconfig failed with error: maximum recursion depth exceeded. This was for a very simple config change ([eb14e0ccb41](https://github.com/WebKit/WebKit/commit/eb14e0ccb41)).

Buildbot version: 2.10.5
Python version: 3.6.8
Twisted version: 21.2.0

Logs:
```
[-] beginning configuration update
[-] Loading configuration from 'master.cfg'
[-] during reconfig:
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
	    return f(*args, **kwargs)
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/service.py", line 526, in reconfigServiceWithBuildbotConfig
	    yield svc.reconfigServiceWithSibling(config_sibling)
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1656, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1571, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.6/site-packages/buildbot/master.py", line 410, in doReconfig
	    yield self.reconfigServiceWithBuildbotConfig(new_config)
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
	    return f(*args, **kwargs)
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/service.py", line 49, in reconfigServiceWithBuildbotConfig
	    yield svc.reconfigServiceWithBuildbotConfig(new_config)
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
	    return f(*args, **kwargs)
	  File "/usr/local/lib/python3.6/site-packages/buildbot/process/measured_service.py", line 31, in reconfigServiceWithBuildbotConfig
	    yield super().reconfigServiceWithBuildbotConfig(new_config)
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
	    return f(*args, **kwargs)
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/service.py", line 526, in reconfigServiceWithBuildbotConfig
	    yield svc.reconfigServiceWithSibling(config_sibling)
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
	    result = current_context.run(g.send, result)
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
	    return f(*args, **kwargs)
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/service.py", line 209, in reconfigServiceWithSibling
	    if self.configured and util.ComparableMixin.isEquivalent(sibling, self):
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 195, in isEquivalent
	    return all(ComparableMixin.isEquivalent(v, them_list[i]) for i, v in enumerate(us_list))
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 195, in <genexpr>
	    return all(ComparableMixin.isEquivalent(v, them_list[i]) for i, v in enumerate(us_list))
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 195, in isEquivalent
	    return all(ComparableMixin.isEquivalent(v, them_list[i]) for i, v in enumerate(us_list))
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 195, in <genexpr>
	    return all(ComparableMixin.isEquivalent(v, them_list[i]) for i, v in enumerate(us_list))
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 196, in isEquivalent
	    return us == them
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 185, in __eq__
	    return self_list == them_list
...
...
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 185, in __eq__
	    return self_list == them_list
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 185, in __eq__
	    return self_list == them_list
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 182, in __eq__
	    (isComparable, self_list, them_list) = self._cmp_common(them)
	  File "/usr/local/lib/python3.6/site-packages/buildbot/util/__init__.py", line 173, in _cmp_common
	    self.__class__, 'compare_attrs', compare_attrs)
	  File "/usr/local/lib/python3.6/site-packages/twisted/python/reflect.py", line 510, in accumulateClassList
	    accumulateClassList(base, attr, listObj)
	  File "/usr/local/lib/python3.6/site-packages/twisted/python/reflect.py", line 510, in accumulateClassList
	    accumulateClassList(base, attr, listObj)
	  File "/usr/local/lib/python3.6/site-packages/twisted/python/reflect.py", line 510, in accumulateClassList
	    accumulateClassList(base, attr, listObj)
	  File "/usr/local/lib/python3.6/site-packages/twisted/python/reflect.py", line 510, in accumulateClassList
	    accumulateClassList(base, attr, listObj)
	  File "/usr/local/lib/python3.6/site-packages/twisted/python/reflect.py", line 510, in accumulateClassList
	    accumulateClassList(base, attr, listObj)
	  File "/usr/local/lib/python3.6/site-packages/twisted/python/reflect.py", line 510, in accumulateClassList
	    accumulateClassList(base, attr, listObj)
	builtins.RecursionError: maximum recursion depth exceeded
	
[-] WARNING: reconfig partially applied; master may malfunction
```

**Comment by p12tic** [comment] 2022-02-02 17:01
Thanks for the bug report.

Unfortunately in this case there is nothing we can do because the logs offer too little information. I guess the root cause is that there was a cyclic dependency between multiple service configuration (one service had another as an attribute and vice-versa). The stack trace indicates that this is related to either `WorkerManager`, `SchedulerManager` or `ChangeManager`. It's hard to tell anything more.

I've created https://github.com/buildbot/buildbot/pull/6354 to add more information to the logs. You can backport the commit to your version of Buildbot and then there would be a chance to understand the issue better if it happens again.

Since there's nothing I can do more, I'm closing the bug report.

**Closed by p12tic** 2022-02-02 17:01 UTC
