### ISSUE TITLE
Buildbot should have a webpage to display all builds for a revision

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3926] opened 2018-01-28 19:52 UTC
One of the primary purpose of Buildbot is to build and test a "commit" to the repository. Developers often want to know whether their commit build and test successfully  (and did not break anything). However, there is no easy way to check build status for a specific commit.

Buildbot does provide console view which displays this information for recent few commits. However, there are multiple reasons because of which a commit might not show up in console view immediately (e.g.: lot of commits to repository, builds start after a long time after commit due to large number of pending build-requests, console view fetching limited number of recent builds). So, it is not guaranteed that the console view will show builds immediately after the commit. Also, if the developer checks console view after long time, it might be showing build for other recent commits. 

So, if a developer want to check builds for his commit, there is no webpage in Buildbot UI which shows this information for sure (console view may or may not show it). There should be some webpage in Buildbot UI where developer can enter a commit-id (revision) and see all corresponding builds.

It can be implemented in multiple ways, some ideas:
- new page having option to enter revision and see corresponding builds
- new page whose url contains revision, e.g.: http://nine.buildbot.net/#/changes/revision-id
- console view having a search button for revision

**Comment by tardyp** [comment] 2018-01-28 20:01
This is a nice idea. It will probably need some more data API / db API in order to allow to search builds by change/sourcestamp

**Comment by uglycoyote** [comment] 2018-03-28 05:56
I would like to see this as well.   We are a game development studio which employs a significant number of artists and other less-technical people who commit content of various kinds which can break the build.   Some of them find it difficult to look at the console page and understand whether or not they have broken the build.

The basic rule is "if every builder has had a green build after your change, then your change is cleared", but even when this rule is understood, it is not always easy to see.

One issue with the stock ```console_view``` is that it doesn't show all changes, only showing changes which have builds associated with them (due to the bit of code below)

            for builder in change.builders
                if builder.builds.length > 0
                    @filtered_changes.push(change)

During peak periods we often have changes entering source control at a much higher rate than the builders can verify them, and we have buildbot set up to always skip ahead to work on the most recent change when it finishes testing what it was working on.  This means that there can be quite a few changes which are between builds and not directly associated with any build and so are omitted from ```console_view```.  Our users found it disconcerting to not see their submitted change on the console, so on my custom console implementation I show all of the changes.  While this means that everyone can see their change and how it relates (temporally) to the builds that are going on, it can mean that the page has a bit more sparse appearance where there's  a fair number of rows with no builds, and one needs to scroll around to figure out whether a green build has happened more recently than the change.

We had a custom "console" interface for Buildbot8 which was aware of which user was viewing it, and when a user would commit a change it automatically would show a popup at the top of the page showing any commits for that user which had not yet "gone green".  (With a message to the effect of "do not go out to lunch or leave for the day until this popup disappears").   People on our team found this useful  but unfortunately we don't have anything like this after moving to Bulidbot9.

So I think rather than having to search by revision number to find the builds associated with it, an even more convenient way to do this is to have a personalized page which shows that specific users changes and all builds associated with them. (could be part of the Console page like the popup I described or could be a separate thing).  This would match changes by ```change.author``` and if you keep it open, your newly submitted changes would appear there.

**Comment by mojca** [comment] 2019-07-05 14:07
@p12tic: Can you please add this issue to the GSOC project? It's basically precisely what we wanted to have as one of the GSOC tasks, so we can as well link this issue there (rather than creating a new one).

**Comment by rajdeepbharati** [comment] 2019-07-05 14:41
@mojca This is exactly what http://ec2-18-191-91-174.us-east-2.compute.amazonaws.com/#/changeslist does (each individual change, when you click on More). Right now the computation is done is the frontend, which is slow, and we were discussing about having an API for that (in some email thread)

**Comment by mojca** [comment] 2019-07-05 14:49
Yes, I know that this is what your view already implements, but as this issue suggest it's unlikely that MacPorts would be the sole interested user of this, so in the long run and after some brainstorming it would be nice to have this functionality as an official buildbot view. (I'm not sure how to sort in case of git's unreliable timestamps, but ...)

And yes, a good API and maybe some database changes are needed for good performance.

**Comment by rajdeepbharati** [comment] 2019-07-18 08:59
@tardyp should we have such a page in the buildbot master? Or should we use the new api in console view instead of Javascript?

**Comment by mojca** [comment] 2019-07-18 15:01
In my (personal) opinion (in long term) it would make sense to:
* use the new api in console view
* add the "calendar widget" to console to let users navigate back in time to see older builds
* extend Builds -> Last Changes (`/#/changes`) (to end up with approximately what you did with `changelist` view, but offer that to each buildbot user out of the box) and:
    * show the corresponding builds
    * have the "calendar widget" to be able to go back in time from that page

I don't know whether it makes more sense and how challenging it would be to rewrite `/#/changes` to vue and offer the described functionality. Maybe just some styling of the code you already wrote + some more testing and fixes would be nearly sufficient for integrating your new view upstream to buildbot repository.

Somewhat (un)related: I wanted to add a random side note, or maybe feature request with a lower priority.
In MacPorts we also (want to) squash multiple commits into a single build to save some CPU cycles.

One thing that might not be the case in other projects is that we then trigger lots of separate builds from that set of changes, but for each of those builds we can pinpoint to the latest commit that actually influenced that package (unless there are merge commits involved and the port was changed in multiple branches).

Example:
* commit A (first): change `python37` and `python36`
* commit B: change `git` and `perl5.30`
* commit C (last): change `python37`

This would trigger rebuilding `git`, `python36`, `python37`, `perl5.30`, but you could more precisely assign `git` to commit B, `python36` to commit A, `python37` to commit C (the latest one touching it), `perl5.30` to commit B.

A question that's relevant for this though: what happens if builders are allowed to squash commits. On builder 1 commits A and B are combined into a single build, while commit C is combined with the next commit D, while on builder 2 all three commits are squashed together into a single build, and commit D is separate. How do you treat such cases? Where are individual builds vs. commits shown?

**Comment by rajdeepbharati** [comment] 2019-07-18 15:36
> I don't know whether it makes more sense and how challenging it would be to rewrite /#/changes to vue and offer the described functionality. Maybe just some styling of the code you already wrote + some more testing and fixes would be nearly sufficient for integrating your new view upstream to buildbot repository.

I'm not sure what you meant by this. Are you talking about this page: https://buildbot.buildbot.net/#/changes ?
I guess buildbot community goal is to progressively migrate to angular (with typescript) from angularjs 1.x, and they don't want their plugins written in Vuejs. Although I would be happy to do it in Vue (I find it somewhat easier) if that is what buildbot community wants.

> A question that's relevant for this though: what happens if builders are allowed to squash commits. On builder 1 commits A and B are combined into a single build, while commit C is combined with the next commit D, while on builder 2 all three commits are squashed together into a single build, and commit D is separate. How do you treat such cases? Where are individual builds vs. commits shown?

I see that squash commits are treated as a single `change`. So there will be a single build. For example:
![Screenshot 2019-07-18 at 8 55 41 PM](https://user-images.githubusercontent.com/30660439/61470315-7424b380-a99e-11e9-9563-5d4227ce1f83.png)

This buildbot ports PR with was squashed contained several commits.

However, I don't think buildbot can determine the individual commits inside a squashed one. This can be a feature request (but for this I guess buildbot would have to get info about the branch which was merged- which might be in a different repository)

**Comment by uglycoyote** [comment] 2019-07-18 18:12
> should we use the new api in console view instead of Javascript logic?

To me this seems like a no brainer, since the console view is a "change centric" view.  One thing I dislike about the current implementation is that it requires you to tune the "number of changes to fetch" and "number of builds to fetch" separately.  Ideally it would just automatically fetch all of the builds for the number of changes you want to display on the page, and the user would not have to guess at the correct ratio between these two numbers.  On our system different types of changes will trigger vastly different numbers of builds (ranging from 50 to 200) which it makes it hard to know what number of builds to request to fill up the page.  

Not to mention that the "num builds to fetch" is also fed in as the number to fetch for `getBuildRequests` and `getBuildSets` -- so by cranking up "num builds to fetch" it is likely requesting way more buildset/buildrequest data than needed.  It is nice if this can all be sorted out on the python side, rather than dealing with all of this in the browser and having to worry about fetching too many of one kind of record or not enough of the other.  

At one point I attempted to implement a "More" button at the bottom of our (custom) console implementation, but some of these issues got in the way and the browser would get bogged down with all of the data, so we had to disable that feature, sadly.

Being able to request "all the builds for change X" via the API makes a lot of these issues go away.

> A question that's relevant for this though: what happens if builders are allowed to squash commits. 

By "squash commits" I assume you mean a builder which skips over commits if the commits are coming in more rapidly than the building can process them (syncing to the next change and effectively "squashing" two or more commits into a single build)?   This is a good question to talk about.  

We do this on our buildbot.  Rather than forcing it to build every change, when the builder becomes idle it will always sync to the latest revision.  In this case you see blank space on the console.  As I mentioned previously in the thread, we made some changes in our console to allow it to show changes which have zero builds associated with them, like Jimmy's change 3 below

![image](https://user-images.githubusercontent.com/2461007/61477147-79084980-a943-11e9-9671-c07c77d6e643.png)

Our users have come to understand that if there's a blank spot on the console for their change's row, they need to look upwards in the same column to find the first build above their row -- which their commit has effectively been "squashed" in to. (This is not obvious to everyone, since it is a game studio we have some less technical users who commit art assets which can break the build and they have more trouble knowing what to look for on the console view).   So if Jimmy wants to know if he broke the build, he needs to look at rows higher up than Change 3.  He didn't break Builder3, but he might have broken Builder1 and Builder2 -- but it could be Jane or Tania's fault.

Implementation-wise, when I query for "all builds corresponding to a change" it is a bit ambiguous what is meant, it could be either:

1. All builds for which `build.got_revision == change.revision`
2. All builds for which `change.revision` is in `build.sourcestamps`

If I'm understanding what you mean by a build "squashing commits" -- it is the case where these two differ.  The sourcestamps are the collection of changes submitted since the builder last built.

In the current implementation of `console_view`, each build only shows up in the row of one change (the build.got_revision change)

But looking at your new implementation of `getBuildsForChange` in #4892, it looks like you took the second route, where e.g. in my example image, build 105 would be returned by calling `getBuildsForChange` changes 3,4, and 5 because those would all be part of the `sourceStamp` list.

So if you try to change console to use your current implementation of `getBuildsForChange`, it might end up looking a bit more like this:

![image](https://user-images.githubusercontent.com/2461007/61477229-9d642600-a943-11e9-8950-d0c2efc8d483.png)

I'm not sure if that's desirable for the console view page, so perhaps `getBuildsForChange` needs a parameter that allows you to choose one method over the other e.g.

`getBuildsForChange( change3, ALL_BUILDS_WITH_CHANGE_IN_SOURCESTAMPS )` vs
`getBuildsForChange( change3, ALL_BUILDS_WITH_CHANGE_IN_GOT_REVISION )`

(of course, you could leave it with the "sourcestamp" implementation and then filter by `got_revision` on the client side, but that seems wasteful as you will be fetching a bunch of redundant data that you are going to throw away.)

Going back to the topic of this particular github issue, (a page for the results of a specific revision), it's not clear what it should show when you go to the page for Jimmy's Change 3.  Which implementation of 'getBuildsForChange' should we use? 

If we use the `got_revision` implementation, then Jimmy's "Change 3" page will be blank -- there are no builds for which the `got_revision` is 3.  So that's not very useful for Jimmy.  He's going to this page to check on whether his change broke the build or not, and it's not telling him anything.

On the other hand if we go with the current "sourcestamps" implementation, then the page is going to show this:

![image](https://user-images.githubusercontent.com/2461007/61478225-f2a13700-a945-11e9-8d73-2d58791c7ca1.png)

which also has some misleading information, or is just not telling the full truth.  Jimmy might jump to the conclusion that he broke the build without realizing that Jane and Tania were involved.

It makes me think that the best solution would be something like an abbreviated version of console_view which shows only the relevant rows, for example if I'm Jane and I want to know about the status of Change 2, it would make sense to show these three rows

![image](https://user-images.githubusercontent.com/2461007/61478971-b66ed600-a947-11e9-9573-49f785b20661.png)

In practice the user will also want to know not just "what are the builds for my change" but also "has the builder been fixed since my change"  so it might be good to include information about subsequent builds which restored the builder to "green" state.

e.g. Jane's Change 2 page might look like this

![image](https://user-images.githubusercontent.com/2461007/61479206-2d0bd380-a948-11e9-81db-dd45ffa1aa6a.png)

but then 20 minutes later when Jimmy checks in a fix, the same page might look like this

![image](https://user-images.githubusercontent.com/2461007/61479355-8411a880-a948-11e9-8476-798e6c96e6f7.png)

at which point Jane can stop worrying about Change 2.  

At that point the page should stop changing.  Even if a builder breaks on a later change like Change 11, we know that it has nothing to do with Change 2 and should not be shown on the Change 2 page.

**Comment by mojca** [comment] 2019-07-18 19:17
> > I don't know whether it makes more sense and how challenging it would be to rewrite /#/changes to vue and offer the described functionality.
> 
> I'm not sure what you meant by this. Are you talking about this page: https://buildbot.buildbot.net/#/changes ?

Yes.

> I guess buildbot community goal is to progressively migrate to angular (with typescript) from angularjs 1.x, and they don't want their plugins written in Vuejs. Although I would be happy to do it in Vue (I find it somewhat easier) if that is what buildbot community wants.

OK, this is something for which I would prefer to hear @tardyp's feedback. My impression was that Vue.js is his top one framework which he would use for everything, if it wasn't for the fact that simply a lot of code needs to be rewritten from scratch to make that happen. But maybe I got that wrong.

> This buildbot ports PR with was squashed contained several commits.

This is different. You made a number of commits and those commits were literally squashed into a single commit before those commits reached the master branch.

The following is an example of two separate commits being built at the same time (to also answer @uglycoyote): https://build.macports.org/builders/ports-10.14_x86_64-watcher/builds/7760

> However, I don't think buildbot can determine the individual commits inside a squashed one. 

It definitely cannot in case of your screenshot. What I'm talking about is when buildbot is busy building and ten commits accumulate before it's free again, and then it builds the code just once. It's precisely the example presented by @uglycoyote, or the one shown above on our old builder.

> We can probably make a feature that checks whether it's a squash commit, then use http://docs.buildbot.net/latest/manual/customization.html#collapse-request-functions

This is what I had in mind: collapsed commits. Squashed was the wrong word which is only used in git terminology.

@uglycoyote raised another quite interesting question. But I would say that implementing the last screenshot is a bit of an overkill. The fix may come after a few hundred builds on that builder, and there might be another hundred failed builds afterwards. Plus, the build success may depend on other parameters. Maybe the green build came from another branch.

**Comment by uglycoyote** [comment] 2019-07-18 21:26
We are using Perforce here so I wasn't aware of the special git meaning of "squashing commits together".   

Perhaps some parts of my ideas are tied to our source control workflow.  

> Plus, the build success may depend on other parameters. Maybe the green build came from another branch.

Unlike git, branching in Perforce is very heavyweight, and therefore rare, so everyone is effectively working out of the same "master" branch, and that's the only branch which is tested by buildbot.  (or occasionally we'll start a new branch and set up a separate buildbot master with a completely independent console view) 

From your comment ("maybe the green build came from another branch") do you mean that within one column (builder) on the console you might have builds using code from multiple different branches?  Is that common for git users of buildbot?  It seems like that would make it a lot harder to read the console view and know when problems are fixed.  Like you say, you would not know whether the green badge represented a fix on the master branch versus some other temporary feature branch.   For this reason I would have thought that even in the git world, one would want the console just to represent the state of the master branch.

**Comment by mojca** [comment] 2019-07-19 06:26
> do you mean that within one column (builder) on the console you might have builds using code from multiple different branches? Is that common for git users of buildbot?

I don't know how common this is among git users (I'm using it on subversion which is unlikely to be more branch-friendly; admittedly just on two branches, `trunk` and `experimental`), but yes, this is what I meant.

I'm using this on https://build.contextgarden.net/#/console (to build two different branches from subversion), but it's much worse with, say, https://build.macports.org/waterfall?tag=10.14, where each build on the same builder is currently building something completely different.

Now that you mentioned this, I came to realise that I should probably start using virtual builders to build different branches (not sure if this is an overkill or not), but there are still plenty of other cases and reasons why subsequent builds might succeed or fail for completely unrelated reasons.

Also, what if you history is more like the following:
```
*   Change 6 (FAIL)
|\
* | Change 5 by Alex (SUCCESS)
| |
* | Change 4 by Tania (FAIL)
| |
| * Change 3 by Jimmy
|/
* Change 2 by Jane (SUCCESS)
|
* Change 1 by Fred (SUCCESS)
```
Without implementing some graph theory in the backend, I fail to see how your third suggestion of what you want to see could ever work reliably. (Maybe it's not an issue with perforce or subversion where such patterns are basically impossible, but I still don't like some ad-hoc solutions that would only cover some cases and not plenty of others.)

**Comment by uglycoyote** [comment] 2019-07-19 17:01
@mojca 
I think I were using git and in a situation with a lot of branching, where builds were being run on all of the branches,  then yes I would probably want a custom git-specific buildbot UI which understood branches.

On the other hand if, like you said, you used separate virtual builders for the different branches, I think my idea would work reasonably for the situation that you depicted.

![image](https://user-images.githubusercontent.com/2461007/61550364-19737200-aa07-11e9-8880-539e879ca516.png)

Then if Jimmy went to the "Change 3" page it would show the top 4 lines of this and he would know that has change might have caused the Build 102 failure, and might have caused the master failure at Build 104.  It would be up to Jimmy to decide whether that's possible based on his knowledge of git. 

It's not perfect though -- with many separate branches being tested it could end up showing a lot of false failure reports that users would have to sort through and know that they could not have possibly caused (e.g. a failure on branch2 can't have been caused by branch1 because you never merge between those two branches)

**Closed** 2019-08-05 21:13 UTC
Labels: feature, gsoc2019, web UI
