### ISSUE TITLE
workers page doesn't list builders with Buildbot 1.0.0

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3956] opened 2018-02-17 23:33 UTC
http://nine.buildbot.net/#/workers doesn't show Builder name (after enabling "Show list of builders for each worker" in http://nine.buildbot.net/#/settings).

Noticing this in my Buildbot instance as well. Restarting buildbot seems to fix this problem temporarily.

This was working fine till Buildbot 0.9.15 and seems like Buildbot 1.0.0 regression

**Comment by aj062** [comment] 2018-03-07 00:58
any ideas @tardyp? 

This is currently happening on http://nine.buildbot.net/#/workers 

<img width="859" alt="screen shot 2018-03-06 at 4 54 38 pm" src="https://user-images.githubusercontent.com/3098702/37067617-7b63c758-215f-11e8-9390-916bf540f758.png">

**Comment by tardyp** [comment] 2018-03-07 08:37
see #3981 for root cause of this issue.

Closing as duplicate.

**Closed by tardyp** 2018-03-07 08:37 UTC
