### ISSUE TITLE
Failed API request during self shutdown writeHeaders writeSequence

### ISSUE THREAD

**Issue by Frodox** [buildbot/buildbot#3705] opened 2017-10-18 11:47 UTC
After initiate grace shutdown with
```python
command=['../sandbox/bin/buildbot', 'stop', '--clean', '--no-wait', '.']
```
and in logs:
```python
2017-10-18 14:41:15+0300 [-] Not shutting down, there are 1 builds running
2017-10-18 14:41:15+0300 [-] Trying shutdown sequence again
...
2017-10-18 14:41:17+0300 [-] BuildMaster is stopped
2017-10-18 14:41:17+0300 [Broker,2,10.11.0.1] Worker.detached(git-updater-wn-hulk)
...
2017-10-18 14:41:17+0300 [Broker,1,10.11.0.1] Worker git-updater-bsys-fly detached from git-updater [bsys-fly]
2017-10-18 14:41:17+0300 [-] while handling API request
        Traceback (most recent call last):
          File "/home/builder/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
...
          File "/home/builder/buildbot/sandbox/lib/python2.7/site-packages/twisted/web/server.py", line 234, in write
            http.Request.write(self, data)
          File "/home/builder/buildbot/sandbox/lib/python2.7/site-packages/twisted/web/http.py", line 1069, in write
            self.channel.writeHeaders(version, code, reason, headers)
        exceptions.AttributeError: 'NoneType' object has no attribute 'writeHeaders'

2017-10-18 14:41:17+0300 [-] While rendering resource:
        Traceback (most recent call last):
          File "/home/builder/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
...
          File "/home/builder/buildbot/sandbox/lib/python2.7/site-packages/twisted/web/http.py", line 1084, in write
            self.channel.writeSequence(toChunk(data))
        exceptions.AttributeError: 'NoneType' object has no attribute 'writeSequence'

2017-10-18 14:41:17+0300 [-] Main loop terminated.
2017-10-18 14:41:17+0300 [-] Server Shut Down.
```
Looks like some race condition?

* Twisted (17.9.0)

**Comment by bruceoberg** [comment] 2017-12-04 02:02
I see this perhaps 1 out of 20 times when I run a step that observes the 'stdio' stream. Exactly the same two exceptions that Frodox reports above.

**Comment by brian-peloton** [comment] 2018-06-22 23:57
Without understanding how any of this code works, this looks like a duplicate of #4045 to me.

**Comment by tardyp** [comment] 2018-06-23 07:10
dupe of #4045 thanks @brian-peloton

**Closed by tardyp** 2018-06-23 07:10 UTC
