### ISSUE TITLE
worker version is shown incorrectly in the UI 

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#5948] opened 2021-03-25 14:10 UTC
worker version is shown incorrectly in the UI, e.g.: on workers page, or individual worker pages.
e.g.: 
http://buildbot.buildbot.net/#/workers
http://buildbot.buildbot.net/#/workers/5
<img width="1187" alt="worker_version_incorrect" src="https://user-images.githubusercontent.com/3098702/112486433-3de22e80-8d52-11eb-83c4-3046a9e42c58.png">

**Comment by aj062** [comment] 2021-03-25 14:45
Seems like this was working fine in buildbot-worker v1.5.0, but stopped working in v1.6.0

**Comment by p12tic** [comment] 2021-03-28 22:50
@tardyp Do you remember if this was an intentional change? I always assumed that Buildbot switched to date-based version for the worker and didn't investigate :))

**Comment by pmisik** [comment] 2021-03-30 14:03
This looks like duplicate of #4464
The problem is missing VERSION file in whl package.

**Comment by p12tic** [comment] 2021-04-09 15:16
Fixed in #5977, will be released as v3.1.1.

**Closed by p12tic** 2021-04-09 15:16 UTC
Labels: bug
