### ISSUE TITLE
smoke tests are very flaky

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#4325] opened 2018-09-13 11:03 UTC
smoke tests have always been kind of flaky.

Since a few days, they are failing on most PRs, still in a flaky way (not all smoke fails, not always the same error)

listing here the failures to try and findout a commonality.

https://nine.buildbot.net/#/builders/10/builds/2901/steps/7/logs/stdio
```
 dashboard page
    ✗ should go to the dashboard page and see no error
      - Failed: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
      While waiting for element with locator - Locator: By(link text, runtests/1). 
      The following tasks were pending:
       - $http: wsgi_dashboards/mydashboard/index.html
```
https://nine.buildbot.net/#/builders/26/builds/2901
```
    check worker page
      ✗ should navigate to the worker page, check the one runtests link
        - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
**************************************************
*                    Failures                    *
**************************************************
1)  check worker page should navigate to the worker page, check the one runtests link
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

**Comment by p12tic** [comment] 2018-11-01 18:55
I remember some failures where the selenium standalone server itself could not be started within the default timeout. Today I was able to very reliably reproduce the failure on my local machine as long as I give the tests less than 2 cores. 

```[20:52:57] I/local - Starting selenium standalone server...
[20:53:57] E/launcher - Error: Error: Timed out waiting for the WebDriver server at http://<ip>:59328/wd/hub
    at onError (/<path>/buildbot/smokes/node_modules/selenium-webdriver/http/util.js:102:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[20:53:57] E/launcher - Process exited with error code 100
```

Looks like it's some race condition within the webdriver itself.

**Comment by p12tic** [comment] 2018-11-01 19:33
E.g. https://nine.buildbot.net/#/builders/26/builds/3039

**Comment by p12tic** [comment] 2018-11-06 16:06
Turns out that hyper somehow sometimes allocates fewer cores than it should according to the instance type. E.g. https://nine.buildbot.net/#/builders/26/builds/3083 fails due only single core being active, but the m2 instance type has 2 cores. A workaround for this is possible, will do a PR.

**Comment by tardyp** [comment] 2018-11-06 16:12
If you have hard evidence on this, we can open a support request on hyper.

Exception in thread "main" java.lang.IllegalStateException: Insufficient configured threads: required=3 < max=3 for QueuedThreadPool[qtp1734161410]@675d3402{STARTED,3<=3<=3,i=3,q=0}[ReservedThreadExecutor@1c93084c{s=0/1,p=0}]

How can you tell this is because the core number is not good?

**Comment by p12tic** [comment] 2018-11-06 18:31
We're basically exposing this issue: https://github.com/SeleniumHQ/selenium/issues/6605. Looks like this just got fixed several hours ago in selenium server 3.141.5. I no longer can reproduce the failure locally on that version.

The flow of logic was that the a thread pool was initialized with thread count being `java.lang.runtime.availableProcessors() * 3` which later turned out to be 3 and insufficient. This implies availableProcessors() returned 1 at the time of the pool initialization. It's implemented using sysconf(_SC_NPROCESSORS_ONLN) on Linux which reads /sys/devices/system/cpu/online on glibc. It could be just that the number of online CPUs is not stable on the VMs on hyper.

I think it's worth letting them know that we have issues with test stability due to unstable CPU throughput at times and whether they have any suggestions of how to work around that.

**Comment by p12tic** [comment] 2018-11-06 21:52
Good idea. I think we could use something like that for the pylint tests. We could run a script that does a minibenchmark every 100 seconds and prints something to console in parallel to the pylint tests and then print top every 1200 seconds to figure out what's failing in these instabilities.

**Comment by p12tic** [comment] 2018-11-06 21:53
As for the smoke tests, I think we fixed or worked around the causes of all recent instabilities in the smoke tests. Thus I think we can close this issue and maybe just create new ones when instabilities are found out again.

**Closed by p12tic** 2018-11-06 21:53 UTC
