### ISSUE TITLE
Inconsistent REST api: buildid vs build_number

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3427] opened 2017-07-09 22:17 UTC
buildbot API is inconsistent. We can fetch all the data using buildid, but not using build_number.

Following API exist: /builds/n:buildid/properties
But there is no corresponding API: /builders/n:builderid/builds/n:build_number/properties

Similarly, following API exist: /builds/n:buildid/changes
But there is no corresponding API: /builders/n:builderid/builds/n:build_number/changes

This results into not being able to fetch all information using build_number. Buildbot should support above missing APIs.

**Comment by tardyp** [comment] 2017-07-10 08:03
This one is pretty easy to implement. Just need to reproduce what is done for the steps and logs endpoint using the  BuildNestingMixin https://github.com/tardyp/buildbot/blob/master/master/buildbot/data/base.py#L97

**Comment by indrajeet307** [comment] 2020-01-25 15:38
Is this still a vaild bug ? 
when I hit the URL 
`localhost:8010/#/builds/n:buildid/properties` it redirects to `localhost:8010/#`

or

`localhost:8010/builds/1/properties` gives a 404

**Comment by rvanlaar** [comment] 2020-05-13 19:54
@indrajeet307 the api is located at /api/v2/ so the url should be: `localhost:8010/api/v2/builds/1/properties

**Comment by trolzen** [comment] 2022-10-06 15:43
@p12tic Looks like this issue was fixed by PR #5557. Shouldn't it be closed as resolved?

**Comment by Squaremann-008** [comment] 2023-09-24 12:57
Is this issue still open ?

**Comment by p12tic** [comment] 2023-09-24 19:46
Indeed, this has been resolved. Thanks for pointing this out.

**Closed by p12tic** 2023-09-24 19:46 UTC
Labels: feature, api, easy, good first issue
