### ISSUE TITLE
Segfault in psycopg2 -> libcrypto; any advice to get more details?

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#4130] opened 2018-06-01 16:39 UTC
We're seeing daily segfaults in buildbot - the entire app just goes away. One of the engineers has setup something that catches the segmentation fault details, but the backtrace only includes the following line:

Backtrace:
/home/buildmaster/buildbot/sandbox/lib/python3.5/site-packages/psycopg2/.libs/./libcrypto-1e9dee74.so.1.0.2n(+0x748be)[0x7f1780c408be]

Not a very good backtrace since there is only one line!

The twistd.log has nothing useful in it.

We are on  Buildbot 1.1.1-dev19, running Postgres on Ubuntu 16.04.3. Psycopg2 is up to date as is libcrypto (1.0.2n)

I'm generally a windows developer, so I wonder if anyone has any ideas on what I could do to get a better stack trace -- ie what was buildbot doing, or what was actually being called in libcrypto?

**Comment by seankelly** [comment] 2018-06-02 17:47
Sounds like a bug in openssl or maybe psycopg2.

**Comment by rodrigc** [comment] 2018-06-02 18:36
It could be a problem with the cryptography library.  Can you try reinstalling the cryptography package with the flags mentioned in this post: https://github.com/pyca/cryptography/issues/3804#issuecomment-317043298

**Comment by tardyp** [comment] 2018-06-07 08:52
any update on this?

**Comment by sphet** [comment] 2018-06-07 17:43
@tardyp I opened a bug at psycopg2 and they had this to say (and then simply closed my issue):

From https://github.com/psycopg/psycopg2/issues/723:

> "It is a known problem with wheel packages (there are a few bugs open about it). Please install psychog from source. See the docs for details."

It isn't clear to me if it is a problem with ALL wheel packages, ALWAYS, or if a forthcoming version will fix it. We have not yet had a chance to install from source. Currently we just reboot it each time it fails and log the errors into an email to our admins.

I'll update this if I hear more.

**Comment by sphet** [comment] 2018-06-20 18:23
Psycopg2 released a new package June 18th, 2018. The wheel is compiled against libcrypto 1.0.2o, so we will see if this fixes the issue for us.

**Comment by sphet** [comment] 2019-04-26 18:05
We're still seeing daily crashes with (an admittedly old pre 1.0 version of buildbot) and psycopg2 libcrypto-6448f03c.so.1.0.2o.

Does anyone remember any issues being fixed in the last year?

**Comment by p12tic** [comment] 2019-04-26 19:55
Unfortunately there's not been any fixes in that area in buildbot. On the other hand It looks like that this issue is caused by a bug in third-party dependency. Additionally, the crash is happening on old, no longer supported version of buildbot which means that no one from the Buildbot development team will investigate it anyway due to lack of time. I therefore close this issue.

I would advise to upgrade to a latest version of Buildbot which will bring updated dependencies and check what happens then. If the crash is still happening, compiling libcrypto with debug symbols will help to gather more information. The lack of stack trace is not surprising if debug symbols are not present - if the frame register is optimized out there's no easy way to walk the stack for whatever captures the crash dump.

**Closed by p12tic** 2019-04-26 19:55 UTC
