### ISSUE TITLE
NightlyTriggerable Scheduler not working

### ISSUE THREAD

**Issue by angeloudy** [buildbot/buildbot#4476] opened 2018-12-13 23:08 UTC
I got the following errors in twisted.log
```
2018-12-13 16:36:42+1100 [-] BuildStep.failed; traceback follows
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
        result = g.send(result)
      File "/usr/local/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 311, in run
        results = yield self.worstStatus(results, rclist, unimportant_brids)
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
        return _cancellableInlineCallbacks(gen)
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
        _inlineCallbacks(None, g, status)
    --- <exception caught here> ---
      File "/usr/local/lib/python3.6/site-packages/buildbot/process/buildstep.py", line 578, in startStep
        self.results = yield self.run()
      File "/usr/local/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 311, in run
        results = yield self.worstStatus(results, rclist, unimportant_brids)
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
        result = g.send(result)
      File "/usr/local/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 205, in worstStatus
        if set(unimportant_brids).issuperset(set(brids_dict.values())):
    builtins.UnboundLocalError: local variable 'brids_dict' referenced before assignment

2018-12-13 16:36:42+1100 [-] releaseLocks(Trigger(schedulerNames=['trigger_
```

And here's the source code that caused the problem.
`/usr/local/lib/python3.6/site-packages/buildbot/steps/trigger.py`
```
192     @defer.inlineCallbacks
193     def worstStatus(self, overall_results, rclist, unimportant_brids):
194         for was_cb, results in rclist:
195             if isinstance(results, tuple):
196                 results, brids_dict = results
197
198             if not was_cb:
199                 yield self.addLogWithFailure(results)
200                 results = EXCEPTION
201
202             # brids_dict.values() represents the list of brids kicked by a certain scheduler.
203             # We want to ignore the result of ANY brid that was kicked off
204             # by an UNimportant scheduler.
205             if set(unimportant_brids).issuperset(set(brids_dict.values())):
206                 continue
207             overall_results = worst_status(overall_results, results)
208         defer.returnValue(overall_results)
```
I added some code the print out the variable `rclist` and it was (True, 0)

I am not sure what is causing the problem, but I can see that this piece of code is not properly written because if  `isinstance(results, tuple)` returns `False`, `brids_dict` would never get assigned.

**Comment by p12tic** [comment] 2021-07-28 23:41
This bug is a duplicate of #5200 which has been fixed in Buildbot v2.7.0. I'm thus closing the issue.

Thanks a lot for reporting it. We should have fixed it sooner, the fix was really simple and was identified in the description of the issue.

**Closed by p12tic** 2021-07-28 23:41 UTC
