### ISSUE TITLE
Expired docs.buildbot.net certificate

### ISSUE THREAD

**Issue by vibbo** [buildbot/buildbot#7511] opened 2024-04-16 10:34 UTC
```
Your connection is not private
Attackers might be trying to steal your information from docs.buildbot.net (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_DATE_INVALID
Subject: docs.buildbot.net

Issuer: R3

Expires on: Apr 15, 2024

Current date: Apr 16, 2024
```

**Comment by pmisik** [comment] 2024-04-19 17:04
It looks like it's fixed.
This is a duplicate of https://github.com/buildbot/buildbot-infra/issues/276

**Closed** 2024-04-19 18:18 UTC
