### ISSUE TITLE
Multi line secrets leaked (i.e. ssh keys)

### ISSUE THREAD

**Issue by PhilippSelenium** [buildbot/buildbot#5020] opened 2019-09-26 14:26 UTC
```
python --version
Python 3.6.8

buildbot --version
Buildbot version: 2.4.1
Twisted version: 19.7.0
```

Config excerpt:
```
steps.ShellCommand(
        command=util.Interpolate("echo '%(secret:single_line_secret)s'")
       )

steps.ShellCommand(
        command=util.Interpolate("echo '%(secret:multi_line_secret)s'"),
)
```

Log output single line secret:
```
echo '<single_line_secret>'
 in dir /home/buildbot/.ssh (timeout 60 secs)
 watching logfiles {}
 argv: b"echo '<single_line_secret>'"
```

Log output multi line secret:
```
echo '<multi_line_secret>'
 in dir /home/buildbot/.ssh (timeout 60 secs)
 watching logfiles {}
 argv: b"echo 'asdf\nfoo\nbar'"
```

**Comment by tardyp** [comment] 2019-09-26 18:28
duplicate of #4793

**Closed by tardyp** 2019-09-26 18:28 UTC
