### ISSUE TITLE
Buildbot 3.6 introduced incomplete logs from remote commands

### ISSUE THREAD

**Issue by vibbo** [buildbot/buildbot#6632] opened 2022-09-13 15:08 UTC
Failed assert message `assert not self.finished` started to appear in Buildbot logs after upgrade to version 3.6. This is the offending line of code: https://github.com/buildbot/buildbot/blob/aa20eeb8c40d04b40501b19c62c52ee333d44c18/master/buildbot/process/log.py#L80

It seems that [recent changes](https://github.com/buildbot/buildbot/commit/5f0234cdb46fab86c9d8eebdc4ed23fa21b918f6#diff-b7636dfe503292a75a7cca895bb9765c7d54da5d7c21f792b70e1cb2c51f5d8cL226)  introduced a bug in following code:
https://github.com/buildbot/buildbot/blob/aa20eeb8c40d04b40501b19c62c52ee333d44c18/master/buildbot/process/remotecommand.py#L378-L401

Function calls to `self.remoteUpdate` on lines 387 & 393 return `Deferred` - `yield` should be used here.

But the next problem is that function `self.remoteComplete` and functions `self.addToLog`, `self.add_stdout_lines`, etc. (called from those  `self.remoteUpdate`s) try to aquire the same lock: `deferredLocked('loglock')`. Thus this now always produces the assert message for logs with `closeWhenFinished=False` - because `self.remoteComplete` closes them before `self.addToLog`, etc. can append the last bit of log. Or it deadlocks if `yield` is used.

**Comment by mokibit** [comment] 2022-09-19 15:07
@vibbo, unfortunately I could not reproduce this bug on my system.
Could you please confirm, that PR https://github.com/buildbot/buildbot/pull/6636 fixes your issue?

**Comment by vibbo** [comment] 2022-09-20 16:42
I have patched my Buildbot and the issue seem to be resolved. Thanks.

You should be able to reproduce using log file with `closeWhenFinished=True` https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/remotecommand.py#L132

**Comment by pmisik** [comment] 2022-09-26 17:31
@p12tic  I think this issue can be closed as PR is merged and @vibbo confirmed issue has been resolved.

**Closed** 2022-09-26 19:07 UTC
