### ISSUE TITLE
MailNotifier throws exception with Python 2.7 & Twisted 17.5.0

### ISSUE THREAD

**Issue by mbunkus** [buildbot/buildbot#3436] opened 2017-07-12 16:01 UTC
I'm using Buildbot 0.9.7 with Python 2.7.13 on Arch Linux. After an update from Twisted 17.1.0 to 17.5.0 (Arch Linux packages) sending emails via the `MailNotifier` reporter fails with the following exception:

```
2017-07-12 16:25:36+0200 [-] sending mail (738 bytes) to ['moritz@bunkus.org']
2017-07-12 16:25:36+0200 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory instance at 0x7f17a00d5cf8>
2017-07-12 16:25:36+0200 [ESMTPSender,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
            return self._dataReceived(data)
          File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
            why = self.lineReceived(line)
          File "/usr/lib/python2.7/site-packages/twisted/mail/smtp.py", line 995, in lineReceived
            why = self._okresponse(self.code, b'\n'.join(self.resp))
          File "/usr/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1044, in smtpState_to
            return self.smtpState_toOrData(0, b'')
          File "/usr/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1062, in smtpState_toOrData
            self.sendLine(b'RCPT TO:' + quoteaddr(self.lastAddress))
          File "/usr/lib/python2.7/site-packages/twisted/mail/smtp.py", line 179, in quoteaddr
            res = email.utils.parseaddr(addr)
          File "/usr/lib/python2.7/email/utils.py", line 214, in parseaddr
            addrs = _AddressList(addr).addresslist
          File "/usr/lib/python2.7/email/_parseaddr.py", line 457, in __init__
            self.addresslist = self.getaddrlist()
          File "/usr/lib/python2.7/email/_parseaddr.py", line 217, in getaddrlist
            while self.pos < len(self.field):
        exceptions.TypeError: object of type 'module' has no len()
```

All five of the following retries fail the same way.

Downgrading Twisted to 17.1.0 and restarting Buildbot makes the problem go away.

Upgrading Buildbot from 0.97 to 0.99.post2 does not change anything; in fact the backtrace shown above was generated by 0.99.post2.

It's quite possible that this is a bug in Twisted (and not in how Buildbot uses Twisted's email module)  and should therefore be reported against Twisted. However, as I'm not a Python developer I can really not make heads or tails of that backtrace. I'll gladly resubmit this to Twisted if this isn't Buildbot's problem.

**Comment by rodrigc** [comment] 2017-07-12 16:10
Duplicate of https://github.com/buildbot/buildbot/issues/3319

**Closed by rodrigc** 2017-07-12 16:10 UTC
