### ISSUE TITLE
buildbot.net SSL/TLS certificate is broken

### ISSUE THREAD

**Issue by djhaskin987** [buildbot/buildbot#3093] opened 2017-03-31 17:50 UTC
My browser told me not to visit it because there was a problem with its certificate.

![image](https://cloud.githubusercontent.com/assets/1186534/24562488/337f8962-1608-11e7-80f3-7e0fc0ebb71c.png)

**Comment by tardyp** [comment] 2017-03-31 18:12
duplicate of https://github.com/buildbot/buildbot-website/issues

**Closed by tardyp** 2017-03-31 18:12 UTC
