### ISSUE TITLE
buildbot.net is inaccessible/down

### ISSUE THREAD

**Issue by jsonar-cpapke** [buildbot/buildbot#6173] opened 2021-08-05 15:54 UTC
At least for me, buildbot.net (and docs.buildbot.net) are inaccessible. I have tried loading them both on a work and home network, as well as over cell data, but I am not able to access either of these sites.

**Comment by levitte** [comment] 2021-08-06 03:41
Duplicate of #6161

**Comment by tardyp** [comment] 2021-08-07 13:30
close as duplicate

**Closed by tardyp** 2021-08-07 13:30 UTC
