### ISSUE TITLE
HTPasswdAuth non-functional

### ISSUE THREAD

**Issue by kallisti5** [buildbot/buildbot#3984] opened 2018-03-09 04:02 UTC
A basic HTPasswordAuth doesn't appear to be functional. (migrating from buildbot 0.8.x)

```python
c['www']['auth'] = util.HTPasswdAuth("htpasswd")
```

Expectation:
 Users to be able to log in

Result:  http 401 return codes, no entries in logs.

**Comment by tardyp** [comment] 2018-03-10 09:28
This is probably a duplicate of  #3126 
Please feel free to contribute a patch for #3126 if you really want htpasswd auth.
I would however suggest to transition to a more modern and secure oauth2 based auth.

**Comment by p12tic** [comment] 2019-04-25 23:36
Closing as duplicate of #3126.

**Closed by p12tic** 2019-04-25 23:36 UTC
