### ISSUE TITLE
group builders per tags

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2892] opened 2017-03-09 16:43 UTC
This ticket is a migrated Trac ticket [3027](http://trac.buildbot.net/ticket/3027)

People contributed to the original ticket: @delanne, @djmitche
Ticket created on: `Nov 14 2014`
Ticket last modified on: `Sep 06 2015`

---

For the waterfall/console web page the builders must be grouped per tags (like in eight)

Tags support is added in PR https://github.com/buildbot/buildbot/pull/1334

---

**Comment by p12tic** [comment] 2019-07-08 08:43
Closing as duplicate of #3470 and #3471. These pages have a little more information.

**Closed by p12tic** 2019-07-08 08:43 UTC
Labels: console_view, eight regression, feature, waterfall_view, web UI
