### ISSUE TITLE
db upgrade broken with sqlalchemy.exc.NoSuchTableError: migration_tmp

### ISSUE THREAD

**Issue by landryb** [buildbot/buildbot#5669] opened 2020-12-06 09:28 UTC
exact same issue as #4978 :
```
upgrading database (sqlite:/state.sqlite)         
Warning: Stopping this process might cause data loss                                                                                                                                                                 
'A serious error has been encountered during the upgrade. The previous upgrade has been likely interrupted. The database has been damaged and automatic recovery is impossible.'
'If you believe this is an error, please submit a bug to the Buildbot project.'                                                                                                                                      
Got fatal Exception on DB                      
Traceback (most recent call last):                                                                                                                                                                                   
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)                                                                                                                                                 
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext                                                                                                              
    return self.currentContext().callWithContext(ctx, func, *args, **kw)                                                                                                                                             
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext                                                                                                               
    return func(*args,**kw)                                                                               
  File "/usr/local/lib/python3.8/site-packages/buildbot/db/pool.py", line 217, in __thd                                                                                                                              
    log.err(e, 'Got fatal Exception on DB')                                                                                                                                                                          
--- <exception caught here> ---                                                                                                                                                                                      
  File "/usr/local/lib/python3.8/site-packages/buildbot/db/pool.py", line 190, in __thd                   
    rv = callable(arg, *args, **kwargs)                                                                                                                                                                              
  File "/usr/local/lib/python3.8/site-packages/buildbot/db/model.py", line 1089, in thd                                                                                                                              
    upgrade(engine)                                                                                                                                                                                                  
  File "/usr/local/lib/python3.8/site-packages/buildbot/db/model.py", line 1053, in upgrade                                                                                                                          
    schema.runchange(version, change, 1)                                                                                                                                                                             
  File "/usr/local/lib/python3.8/site-packages/migrate/versioning/schema.py", line 93, in runchange       
    change.run(self.engine, step)                                                                         
  File "/usr/local/lib/python3.8/site-packages/migrate/versioning/script/py.py", line 154, in run                                                                                                                    
    script_func(engine)                        
  File "/usr/local/lib/python3.8/site-packages/buildbot/db/migrate/versions/058_add_build_data_length.py", line 27, in upgrade                                                                                       
    build_data_table = sautils.Table('build_data', metadata, autoload=True)                               
  File "/usr/local/lib/python3.8/site-packages/buildbot/util/sautils.py", line 62, in Table               
    return sa.Table(*args, **kwargs)                                                                                                                                                                                 
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 469, in __new__                                                                                                                       
    metadata._remove_table(name, schema)          
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__                                                                                                                 
    compat.reraise(exc_type, exc_value, exc_tb)                                                           
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 277, in reraise                                                                                                                      
    raise value
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 464, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 551, in _init
    self._autoload(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 585, in _autoload
    bind.run_callable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2125, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1596, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 414, in reflecttable
    return insp.reflecttable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 645, in reflecttable 
    self._reflect_fk(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 818, in _reflect_fk
    sa_schema.Table(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 469, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 464, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 551, in _init
    self._autoload(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 569, in _autoload
    autoload_with.run_callable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1596, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 414, in reflecttable
    return insp.reflecttable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 645, in reflecttable 
    self._reflect_fk(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 818, in _reflect_fk
    sa_schema.Table(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 469, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 464, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 551, in _init
    self._autoload(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 569, in _autoload
    autoload_with.run_callable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1596, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 414, in reflecttable
    return insp.reflecttable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 645, in reflecttable 
    self._reflect_fk(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 818, in _reflect_fk
    sa_schema.Table(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 469, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 464, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 551, in _init
    self._autoload(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 569, in _autoload
    autoload_with.run_callable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1596, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 414, in reflecttable
    return insp.reflecttable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 645, in reflecttable 
    self._reflect_fk(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 818, in _reflect_fk
    sa_schema.Table(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 469, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 464, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 551, in _init
    self._autoload(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 569, in _autoload
    autoload_with.run_callable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1596, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 414, in reflecttable
    return insp.reflecttable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 639, in reflecttable 
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: migration_tmp
problem while upgrading!:
```

so.. sigh.

**Comment by landryb** [comment] 2020-12-06 09:35
```
sqlite> select * from migrate_version ;
Buildbot|/usr/local/lib/python3.7/site-packages/buildbot/db/migrate|57
```
something about the path to migrate files again, as main python version was updated from 3.7 to 3.8 ?

manually updated the db, didnt help:
```
sqlite> select * from migrate_version ;
Buildbot|/usr/local/lib/python3.7/site-packages/buildbot/db/migrate|57
sqlite> update migrate_version set repository_path='/usr/local/lib/python3.8/site-packages/buildbot/db/migrate';
sqlite> select * from migrate_version ;
Buildbot|/usr/local/lib/python3.8/site-packages/buildbot/db/migrate|57
```

so, manually applied the 58 upgrade like in #4978.
```
sqlite> alter table build_data add column length integer;
sqlite> UPDATE migrate_version set version=58;

```
and upgrade-master doesnt complain anymore
```
upgrading basedir
upgrading database (sqlite:/state.sqlite)
Warning: Stopping this process might cause data loss
upgrade complete
```

after that, 2.9.1 starts fine.

**Comment by p12tic** [comment] 2020-12-07 13:38
@landryb Thanks a lot for the bug report. Indeed, it looks we made a poor assessment of the situation in #4978, your bug is real and needs to be fixed properly.

**Comment by tardyp** [comment] 2020-12-07 15:34
fixed the title of bug. this has nothing to do with 2.9.1, and this looks like an old bug.

**Comment by tardyp** [comment] 2020-12-07 19:41
mmh after reading a bit further of your investigation. I 'm not so sure about the title anymore.

Do you still have your db backup?
Would you care to share it to us, privately?

Pierre

**Comment by landryb** [comment] 2020-12-08 16:17
i have `86290432 Aug 19  2019 state.sqlite.broken` lying around so that's probably a backup i did for the 2.3.1->2.4.0 migration

**Comment by landryb** [comment] 2020-12-08 16:27
can ofc share the database, or run any kind of arbitrary sql on it to help..

**Comment by tardyp** [comment] 2020-12-08 17:37
would it be possible to put that on a cloud storage and share the link to my email?

**Comment by landryb** [comment] 2020-12-09 08:43
mail sent!

**Comment by p12tic** [comment] 2020-12-09 10:28
@tardyp What do you think about investigating switching to [alembic](https://alembic.sqlalchemy.org/en/latest/) for database migrations? sqlalchemy-migrate is no longer supported and 3.0 could be a good breaking point for switching. This is likely to fix issues like this.

The way migrations would work is that we would check for sqlalchemy-migrate migration table first. If it exists and the migration version is not the most recent, we would ask the user to first upgrade to Buildbot 2.10 or whichever is latest (this is the same process as described in our upgrading documentation). Then during upgrade we would delete sqlalchemy-migrate migrations table and initialize the state of alembic. From that point, the migrations would be using the alembic project.

The only way this would not work is that if a user upgrades from a version of Buildbot from before we used migrate which is more than 5 years ago according to the migration code.

**Comment by tardyp** [comment] 2020-12-09 12:42
@p12tic you beat me into suggesting this. I was thinking the same. 100% agree with your proposal.
We can then drop all those migration scripts, and their tests.

**Comment by tardyp** [comment] 2020-12-09 13:00
So I investigated the dump sent by @landryb 

We actually have migration tests on real sqlite3 db.
https://github.com/buildbot/buildbot/blob/ef6233a0686df10d33f495471de9ae32c08cb804/master/buildbot/test/integration/test_upgrade.py#L229

I did import the faulty sqlite db into a tgz, and created a new test with this.
I was able to reproduce the stack trace.
I did add some echo=True, in connection initialization, and got this trace:
```
2020-12-09 11:26:02,665 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,666 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-12-09 11:26:02,666 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,667 INFO sqlalchemy.engine.base.Engine pragma journal_mode = wal
2020-12-09 11:26:02,667 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,670 INFO sqlalchemy.engine.base.Engine select * from migrate_version limit 1
2020-12-09 11:26:02,670 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,672 INFO sqlalchemy.engine.base.Engine select version from migrate_version limit 1
2020-12-09 11:26:02,673 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,677 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_xinfo("migrate_version")
2020-12-09 11:26:02,677 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,679 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,679 INFO sqlalchemy.engine.base.Engine ('migrate_version',)
2020-12-09 11:26:02,679 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("migrate_version")
2020-12-09 11:26:02,680 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,680 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("migrate_version")
2020-12-09 11:26:02,680 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,680 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,680 INFO sqlalchemy.engine.base.Engine ('migrate_version',)
2020-12-09 11:26:02,681 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("migrate_version")
2020-12-09 11:26:02,681 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,682 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("migrate_version")
2020-12-09 11:26:02,682 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,682 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("sqlite_autoindex_migrate_version_1")
2020-12-09 11:26:02,682 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,682 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,682 INFO sqlalchemy.engine.base.Engine ('migrate_version',)
2020-12-09 11:26:02,686 INFO sqlalchemy.engine.base.Engine SELECT migrate_version.repository_id, migrate_version.repository_path, migrate_version.version
FROM migrate_version
WHERE migrate_version.repository_id = ?
2020-12-09 11:26:02,686 INFO sqlalchemy.engine.base.Engine ('Buildbot',)
2020-12-09 11:26:02,688 INFO sqlalchemy.engine.base.Engine pragma foreign_keys=OFF
2020-12-09 11:26:02,688 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,688 INFO sqlalchemy.engine.base.Engine PRAGMA legacy_alter_table = ON
2020-12-09 11:26:02,689 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,690 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_xinfo("steps")
2020-12-09 11:26:02,690 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,692 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,692 INFO sqlalchemy.engine.base.Engine ('steps',)
2020-12-09 11:26:02,692 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("steps")
2020-12-09 11:26:02,692 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,693 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,693 INFO sqlalchemy.engine.base.Engine ('steps',)
2020-12-09 11:26:02,693 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_xinfo("builds")
2020-12-09 11:26:02,694 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,694 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,694 INFO sqlalchemy.engine.base.Engine ('builds',)
2020-12-09 11:26:02,695 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("builds")
2020-12-09 11:26:02,695 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,695 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,695 INFO sqlalchemy.engine.base.Engine ('builds',)
2020-12-09 11:26:02,695 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_xinfo("buildrequests")
2020-12-09 11:26:02,696 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,696 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,697 INFO sqlalchemy.engine.base.Engine ('buildrequests',)
2020-12-09 11:26:02,697 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("buildrequests")
2020-12-09 11:26:02,697 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,697 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,697 INFO sqlalchemy.engine.base.Engine ('buildrequests',)
2020-12-09 11:26:02,698 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_xinfo("buildsets")
2020-12-09 11:26:02,698 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,699 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,699 INFO sqlalchemy.engine.base.Engine ('buildsets',)
2020-12-09 11:26:02,699 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("buildsets")
2020-12-09 11:26:02,699 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,700 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2020-12-09 11:26:02,700 INFO sqlalchemy.engine.base.Engine ('buildsets',)
2020-12-09 11:26:02,700 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_xinfo("migration_tmp")
2020-12-09 11:26:02,700 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,700 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_xinfo("migration_tmp")
2020-12-09 11:26:02,701 INFO sqlalchemy.engine.base.Engine ()
2020-12-09 11:26:02,701 INFO sqlalchemy.engine.base.Engine pragma foreign_keys=ON
2020-12-09 11:26:02,701 INFO sqlalchemy.engine.base.Engine ()
```

It looks like sqlalchemy is reflecting the sqlite3 schema, and clashes by not find the migration_tmp table.


I initially saw no trace of migration_tmp in ``.table``
but when looking at ``.schema``
I see lots of reference to them:

CREATE TABLE logchunks (
	logid INTEGER NOT NULL,
	first_line INTEGER NOT NULL,
	last_line INTEGER NOT NULL,
	content BLOB,
	compressed SMALLINT NOT NULL,
	FOREIGN KEY(logid) REFERENCES "migration_tmp" (id) ON DELETE CASCADE
);

migration_tmp is used when doing alter_tables, migrate is first renaming the table.
I don't know if it has failed at some point to migrate the foreign key configuration.


We have this code for sqlite, which disable foreign keys during migration.
https://github.com/buildbot/buildbot/blob/ef6233a0686df10d33f495471de9ae32c08cb804/master/buildbot/util/sautils.py#L74
introduced here:
https://github.com/tardyp/buildbot/commit/151ca5e6a14322251f946f1e48029d41c002084d

You can find in git history a lot of back and forth with foreign key and sqlite3.
I am not sure if alembic will actually work any better.

foreign key is important to us for the janitor as it used for the delete cascade introduced in 0c8f283d780866fb56056060eee9ca38846d52f7

**Comment by tardyp** [comment] 2020-12-09 19:36
I wasn't able to reproduce the issue via a normal upgrade on the various tests I have made.
So I am not sure what the exact issue that triggered the problem in the first place.
Maybe this was an unfortunate combination of sqlalchemy_migrate + sqlite version that corrupted the database.

I guess the solution would be to hack a fix by forcing the schema to the real schema.
I think this is possible by hacking this table https://sqlite.org/schematab.html

but I don't think this is worth to implement in this project.

**Comment by landryb** [comment] 2020-12-10 07:48
fwiw right now i have sqlite 3.31.1 & sqlalchemy-migrate-0.13.0

**Comment by tardyp** [comment] 2020-12-10 09:48
I think the actual incompatibility was when you did the n-2 upgrade.

**Comment by landryb** [comment] 2020-12-10 10:17
ah, well that was .. quite a while ago. I can look at the software versions for a given timeframe if there's a way to figure out *when* this n-2 upgrade was done. somewhere in the db or logs ? i have twistd.log files dating back to 2018..

**Comment by landryb** [comment] 2020-12-10 10:25
from the logs:
```
twistd.log.5:2019-02-10 11:11:20+0100 [-] The Buildmaster database needs to be upgraded before this version of

twistd.log.4:2019-08-19 19:51:27+0200 [-] The Buildmaster database needs to be upgraded before this version of
twistd.log.4:2019-09-23 15:39:53+0200 [-] The Buildmaster database needs to be upgraded before this version of
twistd.log:2020-12-06 10:24:15+0100 [-] The Buildmaster database needs to be upgraded before this version of
```

#4978 was in august 2019, so the n-2 db upgrade was probably in july 2019 (or feb 2019?).

according to https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/devel/py-buildbot/buildbot/distinfo i upgraded the buildbot port from 2.1.0 to 2.3.1 in may 2019.

around that time according to https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/databases/sqlite3/distinfo we were around sqlite 3.28 or 3.29.

and (also according to https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/databases/py-sqlalchemy-migrate/distinfo) i remember having to upgrade sqlalchemy-migrate from 0.11 to 0.12 in august 2019 *because* the version requirement was bumped in buildbot (fuzzy memory) for 2.4 ?

so maybe the previous db upgrade (that might have caused issues) was with sqlalchemy-migrate 0.11, which is what prompted buildbot to at some point require 0.12 ?

**Comment by landryb** [comment] 2020-12-10 10:30
(now that memory comes back) - i upgraded sqlalchemy-migrate to 0.12 (cf https://github.com/buildbot/buildbot/issues/4978#issuecomment-522680235) in an attempt to fix #4978 so maybe trying to run the 2.3.1 -> 2.4.0 upgrade with sqlalchemy-migrate 0.11 caused the incompatibility ?

**Comment by tardyp** [comment] 2020-12-10 13:43
yeah. I think the bug is fixed in https://review.opendev.org/c/x/sqlalchemy-migrate/+/623564/5
attached to https://bugs.launchpad.net/ubuntu/+source/nova/+bug/1807262
which says 0.12 fixed it. 

So 0.11 definitely had an incompatibility with sqlite3 >= 3.26

**Comment by tardyp** [comment] 2020-12-10 14:24
it will reappear in the next upgrade. basically your foreign keys are broken. its weird that you don't have more problems.

**Comment by landryb** [comment] 2020-12-10 14:28
so there's a way to 'fix' it by recreating foreign key constraints or thats not something possible in sqlite, and its best to dump/restore or something equivalent for sqlite ?

**Comment by tardyp** [comment] 2020-12-10 15:19
Like I said:

> I guess the solution would be to hack a fix by forcing the schema to the real schema.
> I think this is possible by hacking this table https://sqlite.org/schematab.html

With a quick look on this doc, it looks like this is possible to just rewrite the schema table's sql in order to change the constraints.
It might be possible to just copy the schema table from a known good empty database. I haven't tried that. I'll let you play with it.

**Closed** 2020-12-15 01:00 UTC
Labels: bug
