### ISSUE TITLE
Some tasks that are stopped refuse to end, require manager restart to clear

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbot/buildbot#5792] opened 2021-02-11 01:00 UTC
We have occasional incidents when cancelling ongoing buildbot tasks that the task remain in "Building" (Yellow bagde) mode, and is impossible to end even after rebooting the worker or restarting the buildbot worker process (not sure if it is always Windows workers). The result is that the worker cannot start new tasks until the buildbot manager process has been shut down and restarted.

Based on log from the most recent case, a precondition may be that the taskkill operation fails, and this causes some kind of logic state that is not resolved unless the buildbot manager is shut down and restarted. Multiple clicks on the task stop button does not resolve the situation, even after the worker has reconnected.

IIRC loss of connection normally do end the task, but in this case the Stop button had been clicked before the worker process was ended (manually), and it seems that this causes some kind of exception that prevents the buildbot manager from ending the task.

```
2021-02-10 23:43:36+0000 [_GenericHTTPChannelProtocol,6850,1.2.3.4]  <Build OurBuilder number:535 results:warnings>: stopping build: no reason 6
2021-02-10 23:43:36+0000 [_GenericHTTPChannelProtocol,6850,1.2.3.4] RemoteCommand.interrupt <RemoteShellCommand '['git', 'submodule', 'foreach', '--recursive', 'git submodule sync; git submodule update --init --force --checkout']'> no reason
2021-02-10 23:43:36+0000 [Broker (TLSMemoryBIOProtocol),63,1.2.3.4] RemoteCommand.interrupt failed <RemoteShellCommand '['git', 'submodule', 'foreach', '--recursive', 'git submodule sync; git submodule update --init --force --checkout']'> b"Command 'TASKKILL /PID 7128 /T' returned non-zero exit status 128"
2021-02-10 23:43:39+0000 [Broker (TLSMemoryBIOProtocol),64,1.2.3.4] <RemoteShellCommand '['git', 'submodule', 'update', '--init', '--force', '--checkout']'> rc=0
2021-02-10 23:43:39+0000 [-] <RemoteShellCommand '['git', 'submodule', 'foreach', '--recursive', 'git submodule sync; git submodule update --init --force --checkout']'>: RemoteCommand.run [7766]
2021-02-10 23:43:39+0000 [-] command '['git', 'submodule', 'foreach', '--recursive', 'git submodule sync; git submodule update --init --force --checkout']' in dir 'build/vivaldi'

2021-02-10 23:45:03+0000 [Broker (TLSMemoryBIOProtocol),63,1.2.3.4] <Build OurBuilder number:535 results:cancelled>.lostRemote
2021-02-10 23:45:03+0000 [Broker (TLSMemoryBIOProtocol),63,1.2.3.4]  stopping currentStep OurGit(repourl='repo.git', mode='incremental', method='fresh', submodules=True, progress=True, retryFetch=True, name='update', workdir='build/vivaldi', timeout=5400, env={'PATH': ['C:\\Program Files\\Git\\cmd', '${PATH}']}, clobberOnFailure=True, haltOnFailure=True)
2021-02-10 23:45:03+0000 [Broker (TLSMemoryBIOProtocol),63,1.2.3.4] RemoteCommand.interrupt <RemoteShellCommand '['git', 'submodule', 'foreach', '--recursive', 'git submodule sync; git submodule update --init --force --checkout']'> [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
        ]
2021-02-10 23:45:03+0000 [Broker (TLSMemoryBIOProtocol),63,1.2.3.4] Got fatal Exception on DB
        Traceback (most recent call last):
          File "sandbox/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "sandbox/lib/python3.6/site-packages/buildbot/db/pool.py", line 217, in __thd
            log.err(e, 'Got fatal Exception on DB')
        --- <exception caught here> ---
          File "sandbox/lib/python3.6/site-packages/buildbot/db/pool.py", line 190, in __thd
            rv = callable(arg, *args, **kwargs)
          File "sandbox/lib/python3.6/site-packages/buildbot/db/logs.py", line 155, in thdAddLog
            "log with slug '%r' already exists in this step" % (slug,)) from e
        builtins.KeyError: "log with slug ''cancelled'' already exists in this step"

```

**Comment by p12tic** [comment] 2021-03-01 21:11
@YngveNPettersen Thanks for the bug report. I think I've fixed the same issue in 47ce91dea0996e1890cce756ff4f0269d9b4813f. I remember having similar conditions for the issue to be reproduced, so there's high likelihood that the root cause is the same.

The fix is going to be released in 2.10.2 in the coming week.

**Closed by p12tic** 2021-03-01 21:11 UTC
Labels: bug
